### ISSUE TITLE
Expose NavItem and NavGroup in the public_api

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#109]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Export both the `NavItem` and `NavGroup` models in the `public_api.ts` file to allow them to be imported upon implementation from `'@tangoe/goponents'` instead of `'@tangoe/goponents/lib/components/go-side-nav/nav-group.model';`

**Comment by StevenUlmer** [comment]
This looks like it already been done.
