### ISSUE TITLE
[Feature] Support for sticky columns

### ISSUE THREAD

**Issue by AlexOverbeck** [mobi/goponents#118]
### What is the feature that you would like to propose?
We have several requests to be able to create a "frozen" or "sticky" column in our table component. Meaning, when scrolled, the frozen column will stay where it is.

Example: https://material.angular.io/components/table/examples#table-sticky-columns

### Describe the solution you'd like
1. A column in the table component should be able to be designated as "frozen" or "sticky"
2. A "frozen" column should always remain in view as the user scrolls

**Comment by grahamhency** [comment]
I am closing this issue as a result of inactivity and desire. If we find at some point in the future this would be a good feature to add a new issue can be opened and worked.
