### ISSUE TITLE
[BUG] Go Accordion overflow

### ISSUE THREAD

**Issue by akfernun** [mobi/goponents#143]
**Describe the bug**
In the GoAccordion component, there is a class (`.go-accordion-panel__content-container`) that has the `overflow` set to `hidden`. While I'm sure there are instances in which this makes sense, we're running into issues when implementing it in our reporting filters because it is hiding content from drop-downs. 

**Expected behavior**
Remove the overflow so that content from the drop-down will be shown. 

**Screenshots**

####Currently
<img width="324" alt="Screen Shot 2019-08-27 at 11 49 57 AM" src="https://user-images.githubusercontent.com/5104499/63786851-d9829300-c8c0-11e9-8c42-e5c5a2f41924.png">

#### Desired effect

<img width="324" alt="Screen Shot 2019-08-27 at 11 49 40 AM" src="https://user-images.githubusercontent.com/5104499/63786887-e4d5be80-c8c0-11e9-9d40-e31b2b1e65e6.png">

**Comment by grahamhency** [comment]
@akfernun can you try what @AlexOverbeck said and see if that fixes your issue? Ideally, we don't want things showing up outside of the accordion expect when it's an overlay.
