### ISSUE TITLE
Create a sass-lint configuration file

### ISSUE THREAD

**Issue by AlexOverbeck** [mobi/goponents#147]
### What general chore or task would you like to see performed?
We need to implement a sass linter configuration that matches up with the configuration defined in the gosheets repo.

#### gosheets configuration:
https://github.com/mobi/gosheets/blob/master/.sass-lint.yml

**Comment by eligolding** [comment]
Is this to be run as a pre-commit hook? Or is this just to get feedback in the editor? Cuz in gosheets there aren't any npm scripts running the linter.
