### ISSUE TITLE
[Chore] Update Label Fallback Font

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#153]
## Problem

The label fallback font (`go-form__label`) is currently set to Bryant, whereas it should be set to Roboto.

```
.go-form__label {
    color: #313536;
    display: block;
    font-family: "Roboto", "Bryant", "Helvetica", "Arial", sans-serif;
    font-size: .875rem;
    font-weight: 700;
    letter-spacing: 1pt;
    line-height: 1.3;
    padding-bottom: 0.75rem;
}
```

## Suggested Change
Switch the .go-form__label class font-family from `$heading-font-stack` to `$base-font-stack`.

**Comment by grahamhency** [comment]
@jaredami this issue is no longer relevant, closing.
