### ISSUE TITLE
Dark Forms Errors and Hints

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#156]
When creating a form with the dark theme class `go-form--dark` there are no overrides for the font color for both hints and errors. On a dark background both of those show up with black text making it difficult to see them. 

<img width="1116" alt="Screen Shot 2019-08-08 at 11 33 31 AM" src="https://user-images.githubusercontent.com/17074863/62716615-6fb54e80-b9d0-11e9-9a7e-521b700c8b5f.png">

Potential Fix:
overwrite the styles for
```
.go-form__select--error,
.go-form__input--error,
.go-hint
```
inside of the `go-form--dark` class to be `color: $theme-dark-color`

**Comment by AlexOverbeck** [comment]
This should be resolved in #140
