### ISSUE TITLE
[Chore] Correct Navigation Styles

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#163]
### What general chore or task would you like to see performed?
There are a few styles that need corrected in the navigation.

###### Example 
> https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5c9435edae717d314c2b0c69

### Are there any specific steps you would like completed?
1. Side Nav Background color: `$base-dark-secondary`
2. Side Nav Expanded/Active Background color: `$base-dark`

**Comment by eligolding** [comment]
@grahamhency I can take this.

**Comment by eligolding** [comment]
@grahamhency waiting on UX to come back with specs for the hover state of sub items.
