### ISSUE TITLE
[Feature] Layout Footer

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#164]
### What is the feature that you would like to propose?
The layout components need to be able to have a section to render a footer.

_**Example:**_
> https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d4dd6199dada53893b6a783

### Describe the solution you'd like
I think we could simply create a slot for content projection in the go-layout component. Style it slightly to justify-center and that would be sufficient.

### This feature will need to have the following requirements:
1. Included in the layout component
2. Center aligned in the app

**Comment by nilahdad** [comment]
Graham, thanks for correcting me, I think we can go for very simple approach, to avoid lot script.

**Comment by nilahdad** [comment]
Graham, thanks for correcting me, I think we can go for very simple approach, to avoid lot script.
