### ISSUE TITLE
[BUG] Button Group helper classes not working

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#171]
### Description
Using the [button group modifier classes](http://www.tangoe.design/ui-kit/button#button-group) has no effect, due to the encapsulation mode of the button component. This is a regression introduced by yours truly [here](https://github.com/mobi/goponents/pull/138). Previously these styles were all global. 

### Steps to reproduce the behavior:
1. Try to use the `go-button-group` and `go-button-group__item` classes.
2. Open the page in your browser de jour.
3. See how the styles are not being applied.
4. Be sad 😿  

### Expected behavior
Styles should be applied (duh)

### Possible Resolutions
1. Remove encapsulation from the button component (please no)
2. Move there styles to a global file (maybe)
3. Creat a component from button groups (good idea, more work that may not be high priority right now)

**Comment by patryk0605** [comment]
@grahamhency possible fix: https://github.com/mobi/goponents/pull/264
