### ISSUE TITLE
[BUG] Side nav components aren't scrollable

### ISSUE THREAD

**Issue by amit-patra** [mobi/goponents#189]
## Describe the bug
In side nav if it is more that 12 nav items are there it is hiding from web page. I am not getting any scroll there.

## To Reproduce
1. Go to http://www.tangoe.design/ui-kit/accordion
2. Reduce the height of the browser until the side navigation is taller than the viewport.
4. Notice that some of the items become inaccessible.

## Expected behavior
I would expect the side navigation to become scrollable when the height exceeds the viewport.

## Screenshots
![side_nav_issue](https://user-images.githubusercontent.com/1075489/64865068-81f55e80-d606-11e9-8a20-daffddf6f917.png)

**Comment by AlexOverbeck** [comment]
@amit-patra @grahamhency, I've noticed this issue as well. It seems to only be a problem when the side nav becomes taller than the viewport.
