### ISSUE TITLE
[Chore] Update Box Shadows

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#197]
### What general chore or task would you like to see performed?
Box shadows need to be updated to reflect design spec. 
https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d7a967497799142a093ebd2

### Are there any specific steps you would like completed?
- [ ] Update and add new SCSS variables
  - [ ] Update `$global-box-shadow` to the "Normal Box Shadow" in the DSM
  - [ ] Add variable for "High Box Shadow"
  - [ ] Add variable for "Search Box Shadow"
  - [ ] Add variable for "Shell Dropdown Box Shadow"
- [ ] Update components using current shadow that should be using alternate shadow.
  - [ ] `go-action-sheet` should use the "Shell Dropdown Box Shadow"
  - [ ] `go-search` should use the "Search Box Shadow"
  - [ ] `go-header` should use the "High Box Shadow"

**Comment by grahamhency** [comment]
Waiting on UX sync for clarification on usage of shadows, which components get which shadows

**Comment by grahamhency** [comment]
This task has all of the requirements. We're good to go here.

**Comment by patryk0605** [comment]
I can take this issue
