### ISSUE TITLE
[Chore] Page Title Utility Class

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#202]
### What general chore or task would you like to see performed?
We need a way to denote that an element is a page title and apply the appropriate font and other styles.

### Are there any specific steps you would like completed?
* Create a class for page titles
  - Must be prefaced with `go-`
  - The `font-family` should use the `$secondary-font-stack` variable

**Comment by grahamhency** [comment]
Waiting on #191

**Comment by eligolding** [comment]
@grahamhency looks like this is no longer a requirement. I think you can close this.
