### ISSUE TITLE
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by nilahdad** [mobi/goponents#208]
I would like to use ng-select in my Angular 7 project. Here are the problems I'm having with the various versions

"@ng-select/ng-select": "^2.0.7",
ERROR in ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js
Module build failed: Error: ENOENT: no such file or directory, open '....../node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js'

"@ng-select/ng-select": "^3.0.7",
WARNING in ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js 266:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Is there a sweet spot for my environment?

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.16.3
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, core, forms, language-service
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.2
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.15
@angular/material                 7.3.2
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0

**Comment by grahamhency** [comment]
@nilahdad can you provide steps to reproduce this issue?

**Comment by grahamhency** [comment]
@nilahdad I am closing this issue due to 2 months of inactivity. I believe this is a version issue. I would confirm that the correct version of `ng-select` is installed and see if you run into these errors again. 

Additionally, the other 4 projects we have that are utilizing Goponents and the `go-select` that are not having this issue.
