### ISSUE TITLE
[Feature] Side Nav External Links

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#211]
### What is the feature that you would like to propose?
We would like to ability for the side nav component to create an external link.

_**Example:**_
> We would like to have an item that links out to one of our other products

### Describe the solution you'd like
I am thinking maybe create a new interface for external links? That way, `menuItems` can be an array of `NavItem | NavGroup | NavLink`. Then we can detect in the template file that it's a `NavLink` and handle the formatting differently.

### This feature will needs to have the following requirements:
1. Ability to pass external link into side nav
2. Ability to pass external link in place of any `NavItem` that would normally be routed by Angular, including child routes.
3. It should have the same styling as any current `NavItem`
4. It should have a configuration to determine which tab the link opens in, the current tab or a new tab.
5. It should default to open in a new tab

**Comment by patryk0605** [comment]
PR https://github.com/mobi/goponents/pull/214 ready for review
