### ISSUE TITLE
[BUG] Toaster Div Renders with No Toasts

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#217]
**Describe the bug**
The `div` for the `go-toaster` renders even where there are no toasts. This causes problems with the `go-off-canvas` because it has a higher `z-index` and thus makes it difficult to click anything near the bottom of the container.

**To Reproduce**
1. Start up `go-tester`
2. Click on on of the top icons to open the off canvas
3. Inspect the page near the bottom of the off canvas
4. You'll see that you targeted the toaster instead of the off canvas

**Expected behavior**
If there are no toasts in the toaster, we should probably hide the container

**Comment by eligolding** [comment]
Removing the padding on the container will fix this. I have this fixed locally. Feel free to assign this to me.
