### ISSUE TITLE
[Feature] Ability to specify which side to display label on go-switch-toggle

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#233]
### What is the feature that you would like to propose?
We would like the ability to specify a side to display the switch toggle label on.

### Describe the solution you'd like
A binding where we can pass `left` or `right`.

This feature will needs to have the following requirements:
1. The ability to specify which side the label for the go-switch-toggle appears
2. It should default to appear on the right

**Comment by eligolding** [comment]
@grahamhency I got this.
