### ISSUE TITLE
[Feature]: Add a Header and Possibly Icon Input to OffCanvas 

### ISSUE THREAD

**Issue by deotte** [mobi/goponents#240]
### What is the feature that you would like to propose?
This feature will be used to add a customizable header string and additional (possible) icon to the top of the `offCanvas` component. 

We have a need to be able to add headers to our `offCanvas` instance, to better describe to the user what they are seeing on the page and also replicate functionality of what we currently have in Tangoe Mobile. 

### Describe the solution you'd like
 We could add two inputs, `header` and `icon`, but these are arbitrary names and can be changed. These inputs would then be rendered in the `go-off-canvas__header` `div` at the top of `go-off-canvas`.

### Notes
This would likely require a re-design of how the HTML is built for the component.

**Comment by grahamhency** [comment]
@deotte We certainly would like to keep this as consistent as possible. 

To do that, we would probably want to consider keep the close icon regardless with no ability to override.

This would mean that we really would need to be able to pass a title when calling `openOffCanvas`. 

Other requirements:
- It should properly handle when text is too long for the container (no line wrapping)
