### ISSUE TITLE
[Chore] Update Design of Datepicker

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#248]
### What general chore or task would you like to see performed?
The design of our datepicker needs updated.

### Are there any specific steps you would like completed?
1. The styles should be updated to resemble [Material's](https://material.angular.io/components/datepicker/overview)

**Comment by kpmurphh** [comment]
We have designs for the datepicker specified here: 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d9f77bad8f8e4ee4ee8d0f6

**Comment by StevenUlmer** [comment]
> If the user does not wish to use the datepicker, the user should have the option to enter a date in any format. However the format of the date should appear as follows:
YYYY-MM-DD

@kpmurphh I have a couple questions about this statement that's at the top of the DSM page. When it says enter the date in any format, what exactly does that mean? Does that mean a user can enter the date in any format, for example `mm/dd/yyyy` or `yyyy/mm/dd` or `dd/mm/yyyy`? If that's the case then programmatically there are a couple of concerns with that. If a user enters in the date `05/02/2015` there's really no way to tell if that date is supposed to be May 2nd or February 5th. That's one of the main reasons why when creating this we based the format of the date off of the users locale, with the option to always be able to enter in the date as `yyyy/mm/dd` as a fallback. They can also use any of the following to separate the days and months (`.`, `-`, `/`) as long as the days and months are in the correct order based on their locale. In regards to always displaying the date in the `yyyy-mm-dd` format, I understand it adds more consistency and is considered the international standard, but when filling out a form and looking at a date I know at least I would probably expect to see the date in the same format I would write the date on a piece of paper. There aren't very many places where people would actually write the date in that format. I guess my question would be, is it a better User Experience to display the date in international format or to display it in the format that they would have grown up reading it in?

**Comment by kpmurphh** [comment]
@StevenUlmer I've been discussing with the UX team and I understand the reasoning by basing the date format off the user's locale. I think it makes the most sense to do it the way you're describing so let's keep it that way. We just want to make sure the user always understands what date they are entering/choosing. Thanks for your help with this!

**Comment by grahamhency** [comment]
Closed with #350
