### ISSUE TITLE
[Chore] Add New UI Color "Earth" & Update UI Colors

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#249]
### What general chore or task would you like to see performed?
UX has decided to add a new UI color called Earth. This will be in place of the current `ui-color-positive`. Additionally, there are some other minor alternations that are needed.

###### Example 
https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3f2c3d04745c212081590

### Are there any specific steps you would like completed?
- [x] Change `$ui-color-positive` to be `#1D8915`
  - [x] Change `$ui-color-positive-hover` to be `darken($ui-color-positive, 3.5%);`
  - [x] Change `$ui-color-positive-active` to be `darken($ui-color-positive, 7%);`
  - [x] Change `$ui-color-positive-gradient` to be `linear-gradient(to bottom, $ui-color-positive, $ui-color-positive-hover)`
- [x] Change `$ui-color-negative` values
  - [x] Change `$ui-color-negative-hover` to be `darken($ui-color-negative, 3.5%);`
  - [x] Change `$ui-color-negative-active` to be `darken($ui-color-negative, 7%);`
  - [x] Change `$ui-color-negative-gradient` to be `linear-gradient(to bottom, $ui-color-negative, $ui-color-negative-hover)`
  - [x] Remove `$ui-color-negative-dark` and `$ui-color-negative-darker`
- [x] Change `$ui-color-neutral` values
  - [x] Change `$ui-color-neutral-hover` to be `darken($ui-color-neutral, 3.5%);`
  - [x] Change `$ui-color-neutral-active` to be `darken($ui-color-neutral, 7%);`
  - [x] Change `$ui-color-neutral-gradient` to be `linear-gradient(to bottom, $ui-color-neutral, $ui-color-neutral-hover)`
- [x] Add `$ui-color-primary` from current `$ui-color-positive: #00838f;`
  - [x] Add `$ui-color-primary-hover` as `darken($ui-color-primary, 3.5%)`
  - [x] Add `$ui-color-primary-active` as `darken($ui-color-primary, 7%)`
  - [x] Add `$ui-color-primary-gradient` as `linear-gradient(to bottom, $ui-color-primary, $ui-color-primary-hover)`
- [x] Update "Colors" documentation to reflect these changes.

**Comment by eligolding** [comment]
![](https://media.giphy.com/media/mm8TIKFMbGErS/giphy.gif)

**Comment by grahamhency** [comment]
Closed with #331
