### ISSUE TITLE
[Feature] Accordion and Modal Tables

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#285]
### What is the feature that you would like to propose?
UX needs the ability to place tables within a modal.

_**Example:**_
Cloud 3.0 has a need to select multiple groups from a modal table

### Describe the solution you'd like

Modal Example: https://tangoe.invisionapp.com/share/URUHTZLWFQS#/389863115_Add_New_Employee_-_Add_Group

**Comment by patryk0605** [comment]
@grahamhency I'll take the issue

**Comment by Fagiolia1** [comment]
Updated Request. 

Accordion tables are no longer required.

**Comment by patryk0605** [comment]
@grahamhency @StevenUlmer per @Fagiolia1 - this issue has been resolved by the changes made for https://github.com/mobi/goponents/issues/313. No additional changes are required therefor I believe we can close this issue. Attaching screenshot of current implementation for reference: 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7227636/69736889-5cee9300-1101-11ea-87af-ddb228d3271d.png)

**Comment by grahamhency** [comment]
Per @patryk0605's last comment, it seems this issue is no longer relevant. Closing.
