### ISSUE TITLE
[BUG] Accordion Cuts off Datepicker

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#290]
**Describe the bug**
When a datepicker is placed at the bottom of an accordion it is cut off making a date lower in the month unselectable

**To Reproduce**
1. Create a template with a go-accordion in it.
2. Add a go-accordion-panel to the go-accordion
3. Add a go-datepicker inside of the go-accordion-panel
4. Click on the calendar view on the datepicker
5. The end of the datepicker is cut off

**Expected behavior**
I expect the datepicker to be an overlay and not be affected by things like `overflow: hidden` as it is outside of the normal flow of the page.

**Screenshots**
<img width="1135" alt="Screen Shot 2019-10-29 at 4 20 30 PM" src="https://user-images.githubusercontent.com/17074863/67805901-430d5200-fa68-11e9-944c-efbdcece3370.png">

**Comment by eligolding** [comment]
This is also an issue when placing the datepicker in an off-canvas. The `overflow` attributes are cutting it off 😢 

<img width="296" alt="dp1 (1)" src="https://user-images.githubusercontent.com/5261826/70246421-bed47b80-1745-11ea-9081-62e656979296.png">

Note that the styles at the top of the calendar view are also not rendering properly, probably related to being inside the off-canvas, but that might be a completely different issue.

**Comment by StevenUlmer** [comment]
@eligolding The styles will probably be updated/fixed with https://github.com/mobi/goponents/issues/248, so I would just worry about the overflow issues on this one

**Comment by StevenUlmer** [comment]
@eligolding looks like the overflow on the off canvas is also fixed by #248 because it's not wide enough to overflow anymore. The Accordion overflow will still probably be an issue tho. 😁

<img width="301" alt="Screen Shot 2019-12-12 at 9 20 27 AM" src="https://user-images.githubusercontent.com/17074863/70720231-6b23de00-1cc1-11ea-9a72-3872fd4de3a2.png">

**Comment by grahamhency** [comment]
Just looked into this and tested. It looks like this issue has been resolved in some previous PR.. Probably #248.

Screenshot:
<img width="1039" alt="Screen Shot 2020-02-14 at 11 33 01 AM" src="https://user-images.githubusercontent.com/11966331/74549563-da19ef00-4f1d-11ea-8b52-efeda6e0b5dc.png">
