### ISSUE TITLE
[BUG] Expression Changed After Checked on Accordion

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#303]
**Describe the bug**
When implementing the accordion in an off canvas we're getting a `ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'go-accordion-panel__content--slim: undefined'. Current value: 'go-accordion-panel__content--slim: false'` error. This seems to be happening because we're updating the accordion panel from the accordion component after the view is initialized. This seems to be a pretty common problem whenever you update children or parent components in a `ngAfterContentInit` or `ngAfterViewInit` lifecycle method.

**To Reproduce**
1. Create an accordion that get's rendered on the page without setting the property slim.
2. I'm not sure what else triggers this as I can only reproduce this outside of the goponents project.

**Expected behavior**
No js errors when implementing the go-accordion without the slim property

**Screenshots**
<img width="1426" alt="Screen Shot 2019-11-06 at 10 25 36 AM" src="https://user-images.githubusercontent.com/17074863/68311640-d0136500-007f-11ea-8fd7-0c6d70076c35.png">

**Comment by grahamhency** [comment]
Closed with #304
