### ISSUE TITLE
[Feature] Header Bar for "Interior Pages"

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#305]
### What is the feature that you would like to propose?
We need a top header bar with an H2 title on the left and the option for buttons on the right. 

This header bar should be fixed to the top of the page and follow the user as they scrolls down the page.

Here is the DSM information regarding the header bar: 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d7a956118677478a3a5f60c

We would also like the Header Bar to have an option for a back button. This back button would function as a browser back for interior pages within an application. 

For example, if a user selects an invoice from a table of invoices, the Header Bar on the individual invoice page would have a back button attached. This would allow the user to navigate quickly back to the list of invoices instead of having to use the left navigation or their native browser back.

Example of back button on the Header Bar:

https://tangoe.invisionapp.com/share/YJTHRTCFA4X#/382017621_Invoice_Task

**Comment by grahamhency** [comment]
@Fagiolia1 thanks for submitting this.

Are we dropping the "back" functionality requirement?

**Comment by Fagiolia1** [comment]
@grahamhency We'd like to have the back button there as an option. Is it possible this can be configurable? Some screens right now are still going to require this.

**Comment by grahamhency** [comment]
@Fagiolia1 I think so, would you mind adding the specifics of how that thing should work in the description of the task please?

**Comment by jaykravetz** [comment]
I can work on this one

**Comment by jaykravetz** [comment]
@Fagiolia1 Should the back arrow use the browser history or should there be an option to set the go-back-to path (or both)?

**Comment by Fagiolia1** [comment]
@jaykravetz at the moment lets keep browser history. We're considering other ways to display this pages in the future, but for now we're sticking with browser history.

**Comment by grahamhency** [comment]
@Fagiolia1 how about getting rid of it??? :smirk:

What happens if there is no history for the tab?

**Comment by eligolding** [comment]
>how about getting rid of it???

Best. Idea. Ever. 

>What happens if there is no history for the tab?

What I've been doing in my local version of this component in Command Center is pass in a fallback url.

**Comment by Fagiolia1** [comment]
> @Fagiolia1 how about getting rid of it??? 😏
> 
> What happens if there is no history for the tab?

If there is no history, the back arrow should drop.

**Comment by eligolding** [comment]
>the back arrow should drop

Guaranteed bug report: "The entire app is doesn't work! Sometimes the arrow is not there and sometimes it is there and the internet is broken!"

**Comment by Fagiolia1** [comment]
> > the back arrow should drop
> 
> Guaranteed bug report: "The entire app is doesn't work! Sometimes the arrow is not there and sometimes it is there and the internet is broken!"

Good point. We can disable the arrow if there is no browser history. 

As I mentioned before, we're working through a different design, but its still down the line a bit since we have other priorities right now. We're going to have to roll with this design right now due to the looming Cloud launch. Many of the pages require this functionality.

**Comment by grahamhency** [comment]
Closed with #336
