### ISSUE TITLE
[Chore] Update Heading Font Sizes

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#310]
### What general chore or task would you like to see performed?
We need to update the heading font sizes of our `go-heading-x` classes. 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/typeStyles/5c9435edae717d079e2b0c6c

### Are there any specific steps you would like completed?
- [ ] Update the `go-heading-x` classes to design spec (units shown in px in the DSM)
- [ ] Audit usage of the headings in the style guide and update the usage to the appropriate font sizes

**Comment by patryk0605** [comment]
@grahamhency I'll take on this issue.

**Comment by grahamhency** [comment]
Closed with #337
