### ISSUE TITLE
[Feature] Ability to use an Accordion as a card

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#311]
### What is the feature that you would like to propose?
There are certain instances where the accordions could be used outside of the traditional card layout. This means they would no longer have borders and also have a box shadow.

_**Example:**_
> https://tangoe.invisionapp.com/share/URUHTZLWFQS#/screens/389863111
> Scroll down, it's near the bottom

### Describe the solution you'd like
Ideally either a class or a binding that allows for this type of design.

**Comment by patryk0605** [comment]
@grahamhency I'll take the issue

**Comment by grahamhency** [comment]
Closed with #329
