### ISSUE TITLE
[BUG] Side nav active router indicator doesn't work within router-outlet

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#316]
**Describe the bug**
When rendering the go-side-nav within a router-outlet, the active route indicator will not show. This bug did not surface in either go-tester or the style guide, as both of those are using go-layout which renders the [nav](https://github.com/mobi/goponents/blob/ddf55b66164c25309896e7f0f0f3a51f2f85e238/projects/go-lib/src/lib/components/go-layout/go-layout.component.html#L5) before the [router-outlet](https://github.com/mobi/goponents/blob/ddf55b66164c25309896e7f0f0f3a51f2f85e238/projects/go-lib/src/lib/components/go-layout/go-layout.component.html#L9-L11).

My observation is that there is a race condition, in that a menu item is [marked as active during a NavigationEnd event](https://github.com/mobi/goponents/blob/cf261e8fd679de5a35331e1c673a6eff39c65007/projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.ts#L17-L29), but the menu items in the nav service are not set [until the nav component is initialized](https://github.com/mobi/goponents/blob/cf261e8fd679de5a35331e1c673a6eff39c65007/projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts#L21-L22), which in the case of the nav component being rendered in a route will be _after_ that event.

**Expected behavior**
The active nav indicator should work regardless of where the go-side-nav component is rendered.

**Possible Solution**
Instead of listening to router events and then looking for the link that we want to mark as active, perhaps we can detect when [angular marks a link as active](https://angular.io/api/router/RouterLinkActive#isActive) and then find the parent nav group by adding a directive to it and then query it using the `@Host` decorator.

**Comment by grahamhency** [comment]
Should be fixed with #320
