### ISSUE TITLE
[BUG] Scroll Position when Switching Pages

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#325]
**Describe the bug**
When you navigate to a page and scroll to the bottom, that scroll position remains when you navigate to another page. This should not happen. The user should be at the top of the new page when they navigate, not the bottom.

**To Reproduce**
1. Go to a page on the Tangoe.design website.
2. Scroll to the bottom of the page.
3. Navigate to another page using the left navigation.
4. The new page will open at the bottom of the page.

**Expected behavior**
The new page should open at the top of each new page. 

**Screenshots**

**Comment by grahamhency** [comment]
Closed with #335
