### ISSUE TITLE
[Feature] Multi-Tenant Feature in Shell

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#330]
### What is the feature that you would like to propose?
Users need the ability to switch to a different Tenant (or Business as it is described in Mobile). 

### Describe the solution you'd like
We are working on the design right now, but essentially it would be a "business" Material Icon on top. When the user selects the icon, an off-canvas opens up with the Tenant options and a type-ahead search. 

The user can then select a tenant and hit the button at the bottom to  confirm their selection. The Tenant name would appear to the left of the icons on the top of the shell.

I will update this issue with an InVision link once we have a confirmed design. I just wanted to get this down!

**Comment by grahamhency** [comment]
@Fagiolia1 this is possible currently, it must be completed on implementation. I'm going to close this issue because of this.
