### ISSUE TITLE
Unidentified Error -goPonents

### ISSUE THREAD

**Issue by nilahdad** [mobi/goponents#334]
![image](https://user-images.githubusercontent.com/3898847/69793678-f3e54900-11ee-11ea-9cbd-2896b95af218.png)

**Comment by grahamhency** [comment]
Hey @nilahdad, unfortunately this request does not provide us with enough details. I am closing this issue as a result of that.

If you're still receiving this error, please submit a new issue using the `Bug` template and follow the guidelines provided.

If you submit another issue, in the appropriate format, we can look into this issue further.
