### ISSUE TITLE
[Chore] Add Icons to Tables

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#338]
### What general chore or task would you like to see performed?
In the design system we have icons that perform actions on a table. Please add the icons as options to be added to tables. 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d80fd09a0151f3b9e277c1e

**Comment by eligolding** [comment]
This can already be accomplished via [table actions](https://tangoe.design/ui-kit/table/actions). Do the icons need to be built into the table, or is it on the user to use the correct icons?

**Comment by grahamhency** [comment]
@eligolding is correct, that feature should be sufficient. How these function will differ slightly depending on the exact implementation.
