### ISSUE TITLE
[Chore] Update Button Heights 

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#345]
### What general chore or task would you like to see performed?
Button heights need to be 36px as specified in the DSM: 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3f2c3d04745c212081590

**Comment by grahamhency** [comment]
@kpmurphh instead of defining an explicit height, it looks like we might just have a difference in top/bottom padding. Could you provide what that should be in rems please?

**Comment by kpmurphh** [comment]
@grahamhency the padding top/bottom should be .625rem

**Comment by grahamhency** [comment]
Closed with #449
