### ISSUE TITLE
[Chore] Update Toast Designs

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#349]
### What general chore or task would you like to see performed?
Please update toasts to match the styling in the DSM: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d6ecbb61f366d84191d3f6c

**Updates:**
- [x] Left bar should be a solid color - currently gradient
- [x] Icon inside circle should be 20px - currently 16px
- [x] Circle background color should be solid - currently gradient
- [x] Circle should not have a box shadow
- [x] Circle should have 16px/1rem of padding on each side
- [x] Toast Header should be 18px - currently 20px
- [x] There should be no line height on the header
- [x] There should be 4px margin-bottom on the header
- [x] There should be 16px/1rem of padding on the top and bottom

**Comment by grahamhency** [comment]
@kpmurphh would you mind providing a brief outline of what changes are necessary to this?

**Comment by kpmurphh** [comment]
@grahamhency done! sorry about that. i'll do that for anything else i add in the future.

**Comment by grahamhency** [comment]
@kpmurphh, thanks for outlining the difference. I have some questions

1. I believe this should be determined by the content within the toast and will expand/collapse based on the amount of content. This makes for a more flexible and responsive layout.
> Default min height is 64px - currently 80px

2. This change would make these inconsistent with the other areas we utilize these accents. I would recommend either waiting and converting the other instances to solid color as well or not doing this.
> Left bar should be a solid color - currently gradient
> Circle background color should be solid - currently gradient

3. We make use of a `go-heading-x` class here, should we just change the the header class to match these specs?
> There should be no line height on the header 
> There should be 4px margin-bottom on the header
> Toast Header should be 18px - currently 20px

**Comment by kpmurphh** [comment]
hey @grahamhency 

> 1. I believe this should be determined by the content within the toast and will expand/collapse based on the amount of content. This makes for a more flexible and responsive layout.

Agreed. I'm going to remove this one.

> 2. This change would make these inconsistent with the other areas we utilize these accents. I would recommend either waiting and converting the other instances to solid color as well or not doing this.

We want all gradients to be solid colors. I'm working on adding issues to change all the gradients to solid colors. If you'd prefer to wait for me to put them all in that's totally fine!

> 3. We make use of a go-heading-x class here, should we just change the the header class to match these specs?

Yeah that would be great. Thanks!

**Comment by grahamhency** [comment]
Closed with #445
