### ISSUE TITLE
[BUG] go-switch-toggle label placement for long text

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#354]
**Describe the bug**
When the label text for a switch toggle is too long to fit within the width of its parent, it gets pushed down below the toggle.

**To Reproduce**
1. Create a form within a `go-off-canvas`.
2. Add a `go-switch-toggle` to the form with text that is too long to fit horizontally.

**Expected behavior**
The label text for our switch toggles should remain aligned with its toggle button and wrap appropriately.

**Screenshots**
Current behavior:
<img width="300" alt="Screen Shot 2019-12-09 at 10 32 55 AM" src="https://user-images.githubusercontent.com/23343417/70449812-a085bd00-1a70-11ea-94dd-b31b13c7cd8a.png">

Desired behavior:
<img width="296" alt="Screen Shot 2019-12-09 at 10 46 36 AM" src="https://user-images.githubusercontent.com/23343417/70450123-302b6b80-1a71-11ea-8ee1-568b42780214.png">

**Comment by grahamhency** [comment]
Closed with #357
