### ISSUE TITLE
[BUG] Secondary button is 2 pixels taller

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#355]
**Describe the bug**
Given that the secondary button has a border of 1 pixel, the resulting height is 2 pixels taller than the others. This looks funny when it is placed next to another button of a different variant. 

Even though we are setting `box-sizing` to `border-box`, since the height is dynamic based on the font size of the content of the button, the border is adding to the computed height.

**To Reproduce**
1. Render two buttons next to each other, one as "primary" and one as "secondary"
2. Put your glasses on
3. Squint at the screen

**Expected behavior**
Buttons should be the same height.

A solution would be to add a border with same color as background to all buttons.

**Screenshots**
<img width="458" alt="Tangoe 2019-12-09 11-17-11" src="https://user-images.githubusercontent.com/5261826/70453659-286ec580-1a77-11ea-8cb6-cd09f9fd87fb.png">

**Comment by grahamhency** [comment]
Closed with #441
