### ISSUE TITLE
[Feature] Tables in Accordions

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#359]
### What is the feature that you would like to propose?
We need the ability to add data tables to accordions. These tables will have their own actions such as search, filter, etc. 

### Describe the solution you'd like
We have a design already established: 
https://tangoe.invisionapp.com/share/URUHTZLWFQS#/396747554_Invoice_Detail

The table wouldn't rest on a card, but would be flush on the accordion once it opens.

**Comment by patryk0605** [comment]
I can take this one

**Comment by grahamhency** [comment]
Closed with #379
