### ISSUE TITLE
[Feature] Add Search Functionality to Tables

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#360]
### What is the feature that you would like to propose?
Please add a search bar toggle to tables for the user to search through a few columns designated by developer. 

The search bar will appear above the table headers and below the table title and control.

_**Example:**_
We have a need for the user to quickly search through a data table. The designated columns that will be queried would be assigned by the developer implementing the table. 

### Describe the solution you'd like
https://tangoe.invisionapp.com/share/URUHTZLWFQS#/397184150_Invoice_List

The search bar should be 1 rem from the Table Title and 1 rem from the table column headers.

The search bar should have a debounce approach where the search is not activated until the user is done type for a certain time limit. This time limit should be configurable by the developer.

**Comment by grahamhency** [comment]
Closed with #411
