### ISSUE TITLE
[BUG] incorrect datepicker font-color for dark mode

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#363]
**Describe the bug**
Some of the font-colors for our `go-datepicker` inherit from their parent and thus are turned white when their parent uses our dark theme, making the font illegible on the white background of the datepicker.

**To Reproduce**
1. Add a `go-datepicker` within an element that uses our dark theme (e.g. a `go-off-canvas`).
2. Open the calendar view of the datepicker to see the problem.

**Expected behavior**
The font-colors of the datepicker should be set to black so that they are always visible on the white background of the datepicker.

**Screenshots**
Current behavior:
![Screen Shot 2019-12-11 at 1 35 26 PM](https://user-images.githubusercontent.com/23343417/70650049-56413f00-1c1c-11ea-8470-c5056e341d1d.png)

Desired behavior:
![Screen Shot 2019-12-11 at 1 36 50 PM](https://user-images.githubusercontent.com/23343417/70650019-49245000-1c1c-11ea-8a62-6eb51b00536d.png)

**Comment by grahamhency** [comment]
Closed with #364
