### ISSUE TITLE
[Chore] Update Table Actions Design

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#368]
### What general chore or task would you like to see performed?
Please update design of table actions: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5df8e955421285ca004f03df

- [ ] Action icons should be size 1.5rem - currently 1rem
- [ ] Hover color of circle should be #F0F0F0 - currently #B1B1B1

**Comment by grahamhency** [comment]
@kpmurphh the hover color is handled by the `icon-button` which has been updated. The only other item here is the font size and this can be accomplished on implementation. As a result, I am going to close this issue.
