### ISSUE TITLE
[BUG] Empty Label Elements on Form Inputs

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#369]
**Describe the bug**
Our form input components render an empty `label` element when no value is passed into their `label` input, which creates unwanted spacing above those inputs.

**To Reproduce**
1. Implement one of our form input components (`go-input`, `go-select`,`go-text-area`, `go-file-upload`, or `go-switch-toggle`) without passing a value to its `label` input.
2. Inspect the element and view the empty `label` that is rendered.

**Expected behavior**
When no `label` value is provided to our form components, it should not render a `label` element at all.

**Screenshots**
Current behavior:
<img width="485" alt="Screen Shot 2019-12-17 at 12 28 44 PM" src="https://user-images.githubusercontent.com/23343417/71019869-22a55f80-20c9-11ea-9ede-23610b192506.png">

Expected behavior:
<img width="496" alt="Screen Shot 2019-12-17 at 12 29 43 PM" src="https://user-images.githubusercontent.com/23343417/71019851-16b99d80-20c9-11ea-9f6c-5c8e60be5799.png">

**Comment by grahamhency** [comment]
Closed with #372
