### ISSUE TITLE
GoIcon busted

### ISSUE THREAD

**Issue by akfernun** [mobi/goponents#37]
It appears as if the `goIcon` component is busted. Instead of rendering the actual icon, it renders the text. Below is an image of what the icon looks like after upgrading to the most recent version. 

<img width="1335" alt="Screen Shot 2019-05-12 at 1 36 39 PM" src="https://user-images.githubusercontent.com/5104499/57585811-35184480-74bb-11e9-91d9-c5753cfad663.png">

In the future, we should consider writing tests around this functionality before releasing.

**Comment by AlexOverbeck** [comment]
This is a result of not being on the more recent versions of `gosheets`.
