### ISSUE TITLE
[Chore] Update Form Hint/Error Design

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#370]
### What general chore or task would you like to see performed?
Please make design changes to the form hint/error.

Form Hint: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d4d8ddc9dada56e8ab66b9b
Form Error: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5ddd86f1a576d83fccecbc03

**Form Hint/Error** (i imagine they are the same/similar component?)
- [ ] There should be a margin of 4px/.25rem on top of the hints - currently 8px/.5rem
- [ ] Padding to the left of the hint bar should be 8px/.5rem - currently 12px/.75rem
- [ ] Form hint left bar color should be #B1B1B1 @ 50% opacity - currently #B1B1B1

**Just Error**
- [ ] Label should be color Horizon and Medium font weight
- [ ] Hint bar should be color Horizon - currently gradient

**Comment by grahamhency** [comment]
@kpmurphh we will probably want to update the `positive` and `neutral` colors to not be gradients either. 
> Hint bar should be color Horizon - currently gradient

**Comment by grahamhency** [comment]
Closed with #383
