### ISSUE TITLE
[Feature] Ability to use GroupBy in go-select

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#374]
### What is the feature that you would like to propose?
Please provide a clear and concise description of what the feature is and how it will be used.

In certain situations we want to group selectable options by a  characteristic on that options. For example a list of carrier accounts that are grouped by the carrier. 

### Describe the solution you'd like
A clear and concise description of what you want to see built.

There should be an input on the go-select component that takes in an attribute to group by. 

https://github.com/ng-select/ng-select#inputs [groupBy]
ng-select already supports this so really the only need is to add the attribute on the component and connect it to the ng-select in the html and then add documentation around it.

**Comment by grahamhency** [comment]
Closed with #423
