### ISSUE TITLE
[Chore] Add rows input to <go-text-area>

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#380]
### What general chore or task would you like to see performed?
We should add a `rows` input to our `go-text-area` component to enable users to specify the default height of a text-area.

### Are there any specific steps you would like completed?
_Insert a list of requirements or recommendations._
1. Add `rows` input to `go-text-area`.
2. Update the text-area docs accordingly.

**Comment by grahamhency** [comment]
Closed with #381
