### ISSUE TITLE
[Chore] Create a Required Asterisk for Required Fields in a Form

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#394]
### What general chore or task would you like to see performed?
We would like the ability to have a red asterisk next to a form label when that field is required. 

###### Example 
Here are the DSM links for the specs surrounding the red asterisk for required fields: 
https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3f2bd5fbc24c9a64bc2ec

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/asset/components/5d6fd327cd1b60161cdf2023

**Comment by grahamhency** [comment]
Closed with #419
