### ISSUE TITLE
[Feature] Add ability to display filters to go-table header

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#395]
### What general chore or task would you like to see performed?
When a user filters item on a data table, the "pills" that display these filters should appear within the table if the table has a filter action icon within it.

The user should be able to remove these filter tokens and the table should reload with the new results.

###### Example 
Here are a few DSM links with the Filter "pills" along with their treatment when a search box is present.

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d80fd09a0151f3b9e277c1e

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d78f66e1c2686d33b530c17

**Comment by grahamhency** [comment]
This should be done after #397 has been merged.

**Comment by grahamhency** [comment]
Closed with #442
