### ISSUE TITLE
[Feature] Accordion Counter 

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#396]
### What is the feature that you would like to propose?
We have a need to display the count of a closed accordion when that accordion includes a data table. 

_**Example:**_
For example, if a closed accordion table has 429 data elements within it, we want the user  to know this information before having to open and close an accordion. This allows the user to know ahead of time whether an accordion has data within it rather than having to click and check manually.

### Describe the solution you'd like
The design of the count is not yet documented within the DSM, but it has a similar appearance to the "Filter Pill" It would appear right next to the title of the accordion with a background color of Nebula and a font color of white. 

We will update the exact specifications of these counts once this item is taken on. This feature relies on https://github.com/mobi/goponents/issues/359

**Comment by kpmurphh** [comment]
Design specs for this can be found here: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5e135527609d76e528cdb901

**Comment by grahamhency** [comment]
We will need two tasks to make this work, one is already in the works.
- Firstly, the `go-pill` #398 
- Secondly, the ability to pass HTML into the Accordion Panel Header, #417 

Afterwards, this approach will be done upon implementation. I'll close this issue once we merge those other two PR's.

**Comment by grahamhency** [comment]
This has been completed by the two PR's mentioned in the previous comment. Closed.
