### ISSUE TITLE
[Feature] Create a Pill component

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#397]
### What is the feature that you would like to propose?
There are a few spots where we make use of "pill", tables, reporting, etc.

_**Example:**_
> https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d78f66e1c2686d33b530c17

### Describe the solution you'd like
A dismiss-able component that looks similar to a button (see DSM link above).

This feature will needs to have the following requirements:
1. Ability to pass in a string of text as the title
2. Ability to dismiss the pill, similar to toasts

**Comment by eligolding** [comment]
@grahamhency I can take this.

**Comment by grahamhency** [comment]
Closed with #398
