### ISSUE TITLE
[Feature] Nested Tree

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#400]
### What is the feature that you would like to propose?
We need the ability to have a Nested Tree. Inside this tree, the elements would need to be editable. This would be accomplished with a hover and a pencil icon on the nested element.

_**Example:**_
Material and Angular already have a tree component in place: 
https://material.angular.io/components/tree/overview

We would like to replicate this design.

### Describe the solution you'd like
We will fill in this request with a more concrete design as we gain more information surrounding our needs.

**Comment by patryk0605** [comment]
I'll take this issue and create a very basic component that understands how to create a tree like structure from a config. I'll try to keep styling to a minimum and then we can open another issue to style it however we please.

**Comment by Fagiolia1** [comment]
Thanks @patryk0605 . I designed a very basic design that incorporates the edit functionality:

https://tangoe.invisionapp.com/share/URUHTZLWFQS#/402048252_Tree_Design
