### ISSUE TITLE
[BUG] Form Field Doesn't Fully Expand

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#401]
**Describe the bug**
On occasion, the form input field does not extend fully. 

**To Reproduce**
Brought this issue up to Graham and he replied "Looks like there is a resize css property that is causing the issue."

![image](https://user-images.githubusercontent.com/8883257/72101957-dcbc6f80-32f3-11ea-8fdd-cd7394cf1847.png)

**Comment by grahamhency** [comment]
Closed with #416
