### ISSUE TITLE
[BUG] Change detection in GoDatePicker seems to not be working

### ISSUE THREAD

**Issue by jaykravetz** [mobi/goponents#402]
**Describe the bug**
Calling `setValue` on a FormControl that is bound to a `go-datepicker` does not update the datepicker's value 

**To Reproduce**
1. Add go-datepicker to any component
2. Inside an async callback (`setTimeout`, etc), call `setValue` on the datepicker's `FormControl`
3. The datepicker field will not be updated

**Expected behavior**
Calling `setValue` on a datepicker's `FormComponent` should update the datepickers value and display the date in the view

**Screenshots**
See example [test case](https://github.com/jaykravetz/goponents/commit/2ea45726d0a4639e5b6fffc9e763b00f326cf024#diff-4feeb60806a53a6ff9ee7a9a6bb20e89R1)

**Comment by patryk0605** [comment]
I'll take this

**Comment by grahamhency** [comment]
Closed with #405
