### ISSUE TITLE
[Chore] Table in Modal Design Changes

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#403]
### What general chore or task would you like to see performed?
Can we please change the design of the table within a modal from the current design of the table being within a card to a table resting on the background and being full-width?

For example: 
![image](https://user-images.githubusercontent.com/8883257/72265706-f9ee8800-35ea-11ea-91f8-f8868e265d84.png)
Table should be full width and not contained within a card if within a modal.

**Comment by patryk0605** [comment]
I'll take this

**Comment by patryk0605** [comment]
@grahamhency per discussion with @Fagiolia1 and Kim - we agreed the `renderBoxShadows` option covers this issue already, so no other changes are required. For reference: 

![image](https://user-images.githubusercontent.com/7227636/72637185-b79cb200-392e-11ea-997b-050b3769c559.png)

**Comment by grahamhency** [comment]
@patryk0605 great, thanks for posting that response. Closing.
