### ISSUE TITLE
[BUG] Table Pagination in Modal Closes Modal

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#404]
**Describe the bug**
When a user opens a modal with a table and switches the pages using the page numbers, the modal closes. If the user uses the arrow icons, the table switches pages as expected.

**To Reproduce**
Open a modal with a table included. 
Switch the pages using the page number.
The modal will close.

**Expected behavior**
The modal should remain open and switch the page.

**Screenshots**

**Comment by patryk0605** [comment]
I'll take this

**Comment by grahamhency** [comment]
Closed with #410
