### ISSUE TITLE
[BUG] Negative Icon Modifier

### ISSUE THREAD

**Issue by escharna** [mobi/goponents#406]
**Describe the bug**
As per the documentation, adding a negative icon modifier should display a red color.  However, it displays in white.

**To Reproduce**
Add a go-icon component and give it an icon modifier of negative.  View the page.  The icon will be white instead of red.

**Expected behavior**
The icon should be red as per the documentation

**Screenshots**
<img width="793" alt="Screen Shot 2020-01-13 at 3 15 34 PM" src="https://user-images.githubusercontent.com/6865003/72289046-4603f180-3618-11ea-9b87-71f46cb2c936.png">

<img width="333" alt="Screen Shot 2020-01-13 at 3 15 37 PM" src="https://user-images.githubusercontent.com/6865003/72289054-49977880-3618-11ea-98d7-62369ef82984.png">

**Comment by grahamhency** [comment]
To clarify on this, the icon should not be red and the functionality is correct. What needs adjusted is the documentation:
- We should not document the `negative`, `neutral`, or `positive` modifiers. 
- We should document the `dark` modifer

**Comment by grahamhency** [comment]
Closed with #433
