### ISSUE TITLE
[Chore] Uniform styling for Form Inputs

### ISSUE THREAD

**Issue by Ashygoyal** [mobi/goponents#407]
### What general chore or task would you like to see performed?
The border color for `<go-input>` and `<go-select>` is currently different. When used together in a form, the appearance of these two doesn't gel. Refer to the screenshots below.
This is also true for the font color property in both components.

###### Example 
Refer to the screenshots below:

<img width="542" alt="FI1" src="https://user-images.githubusercontent.com/3825309/72323325-73ab7200-36ce-11ea-888f-dc91bdf9a3af.PNG">
-------------------------------------------------------------------------------------------------------------
<img width="366" alt="FI2" src="https://user-images.githubusercontent.com/3825309/72323329-74dc9f00-36ce-11ea-8d58-6d563b48ca73.PNG">

**Comment by grahamhency** [comment]
Closed with #464
