### ISSUE TITLE
[BUG] GoSelect Should Truncate Long Select Options

### ISSUE THREAD

**Issue by mwagz** [mobi/goponents#408]
**Describe the bug**
In GoSelect, when an option's text extends beyond the boundary of the select box, after selecting this option, the select box grows to fit the entire string of text.

**To Reproduce**
TypeScript:
```typescript
// some.component.ts
// ...
someOptions: { label: string, value: number }[] = [{
  label: 'Bulk Suspend Lines with Inactive Owner',
  value: 123
}];
// ...
```
HTML:
```html
<!-- some.component.html -->
<div class="size">
  <go-select
    bindLabel="label"
    bindValue="value"
    [control]="form.get('someControl')"
    [items]="someOptions"
    label="Options"
    [loading]="loading"
    placeholder="Select an Option"
  ></go-select>
</div>
```
CSS
```scss
/* some.component.scss */
.size {
  width: 250px;
}
```

**Expected behavior**
It should truncate the text 

**Screenshots**
![GoSelectBug](https://user-images.githubusercontent.com/22661110/72470695-38cd3b00-37af-11ea-9119-2a9afa212da1.gif)

**Comment by grahamhency** [comment]
This actually does happen when used inside of an element with a specific width, closing.
