### ISSUE TITLE
[Feature] Ability to prevent users from clearing value go-select

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#409]
### What is the feature that you would like to propose?
Sometimes items are required for a select and users shouldn't have to opportunity to submit a form with out selecting a value. Part of a good ux for this is that after they select a value they shouldn't be able to deselect the value only change the value selected.

<img width="431" alt="Screen Shot 2020-01-16 at 11 20 50 AM" src="https://user-images.githubusercontent.com/17074863/72542829-c44bd800-3852-11ea-9ba6-8efb46fed5da.png">

### Describe the solution you'd like
1. Implement [clearable] from ng-select into the go-select. Setting clearable to false removes the x and the ability to deselect a value.

**Comment by Fagiolia1** [comment]
The UX team thinks that the x should remain even if the field is a required field. If we remove an x on only certain selects, it will create confusion for the user as it is not specifically outlined why the x is missing. 

The users, by default, have an option to submit the form without a value within the select menu. Removing the x just limits control for the user. We feel as this breaks consistency across selects. 

On a side note, we need the ability to have a basic select menu without the ability to search.

**Comment by grahamhency** [comment]
@Fagiolia1 thanks for the response here. I think that's fine if you all think we should keep it. I'll go ahead and close this issue, but please if you wouldn't mind creating a new issue for this:
> On a side note, we need the ability to have a basic select menu without the ability to search.
