### ISSUE TITLE
[BUG] Header Bar Shadow and Select Boxes Overlap

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#415]
**Describe the bug**
When using the header bar and scrolling down a form, the box shadow from the header bar goes behind the ng-select inputs. 

![image](https://user-images.githubusercontent.com/8883257/72816187-c5577d80-3c35-11ea-805b-6ab79e71ee1a.png)

**To Reproduce**
1. Go to any form with a header bar and a select input.
2. Scroll down so the header bar overlaps the select input.
3. See the box shadow go behind the input.

**Expected behavior**
The box shadow should appear on top of the input as it does other inputs. Playing around with the DevTools a bit, I was able to fix the issue using a z-index of 10 on the header bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/72816187-c5577d80-3c35-11ea-805b-6ab79e71ee1a.png) - Before

![image](https://user-images.githubusercontent.com/8883257/72816382-0a7baf80-3c36-11ea-953d-2f17adf8a13b.png) - After z-index is applied

**Comment by Fagiolia1** [comment]
This behavior is also occurring when the Header Bar overlaps an Accordion as well.

**Comment by grahamhency** [comment]
Closed with #447
