### ISSUE TITLE
[Chore] Update Shell Hamburger Hover

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#424]
### What general chore or task would you like to see performed?
Please update hamburger icon hover state to the following:

- Icon should not change color
- Background should be a circle (like all the other hovers) 36px in height and width and color should change to $base-primary-hover.

Example of how it should look is here: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3d1f5803d26ccb3149a2f

**Comment by grahamhency** [comment]
@kpmurphh I'm struggling a little bit with how best to implement this. If you recall, we brand the app for other companies so we cannot specifically set the background hover color to a brand color. There might be a way to do some calculations around darkening the hover background of icon buttons to work universally.

Here are three screenshots that use the same background for the icon-button. Thought's on this? It would allow us to use the same component everywhere. The only downside I see to this is that it darkens the hover state on a light bg a bit.
![Screen Shot 2020-02-05 at 9 55 04 AM](https://user-images.githubusercontent.com/11966331/73853046-3a15e480-47fe-11ea-8bfc-c9eacbc3fbf9.png)
![Screen Shot 2020-02-05 at 9 55 45 AM](https://user-images.githubusercontent.com/11966331/73853048-3a15e480-47fe-11ea-8909-4c72df3a31d1.png)
![Screen Shot 2020-02-05 at 9 56 14 AM](https://user-images.githubusercontent.com/11966331/73853049-3aae7b00-47fe-11ea-8ad2-1de31519d787.png)

**Comment by cosmicdust73** [comment]
@grahamhency  @kpmurphh Not loving that gray color across the 3 examples. Tangoe is our primary concern right now (per discussions with Ron), and 10% darken of Tangoe's brand color looks best in this case, per Kim's mockup. Not seeing a way this can be handled with a common component everywhere, since white labels need to darken the white base color on hover, and a dark theme will need to lighten the black base color on hover.

**Comment by kpmurphh** [comment]
Hey @grahamhency, anyway we can prioritize this issue? For the time being can we do what we have in the example linked and then we'll work on a more feasible option for whitelabeling in the future?

**Comment by grahamhency** [comment]
@kpmurphh yeah. I think we can probably come up with a way to do the branded state vs non branded. I'll look into this.
