### ISSUE TITLE
[Chore] Modal Height Adjustment

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#426]
### What general chore or task would you like to see performed?
When opening a modal with a large vertical area, a lot of the content gets cut off. Can we modify the modal components a bit to fit more on the page? 

###### Example 
By removing the max-height: 80% from .go-modal__container, .go-modal__container-xl and adding padding:2rem to .go-modal.go-modal--visible, the modal's height fits the page much better while also avoiding content overflowing out of the browser window.

### Are there any specific steps you would like completed?
_Insert a list of requirements or recommendations._
1. Remove max-height:80% from go-modal__container, .go-modal__container-xl
2. Add padding:2rem to .go-modal.go-modal--visible

**Comment by grahamhency** [comment]
Closed with #446
