### ISSUE TITLE
[BUG] Required Selection Inputs Highlight Red if Cleared

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#427]
**Describe the bug**
When a selection input is clicked on, filled in then cleared, the red highlight remains. We would like to remove this red outline and have the validation taken care of on submit/save.

**To Reproduce**
1. Go to a form with a selection input.
2. Click on the input and search and select an option.
3. Hit the x to clear the input.
4. See the red outline around the element even when you click off the element.

**Expected behavior**
This action does not occur with standard input elements that are required, thus we should eliminate it from this select input. The validation should occur when the user submits or saves.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/73194503-4ad9a280-40fa-11ea-8bfb-8c3860797e84.png)
![image](https://user-images.githubusercontent.com/8883257/73194528-53ca7400-40fa-11ea-9a04-d00f0c64bfc6.png)

**Comment by grahamhency** [comment]
Closed with #464
