### ISSUE TITLE
[Feature] Table with 100% width and no "card" styling

### ISSUE THREAD

**Issue by jaykravetz** [mobi/goponents#430]
### What is the feature that you would like to propose?
We have a need for tables in accordion panels that fill the entire panel. The Tables should not have the "card" styling either.

![image](https://user-images.githubusercontent.com/2780584/73490765-2e986880-437b-11ea-9d55-aaf7c761348e.png)

This feature will satisfy the UX requirements for data grids inside accordions.
_**Example:**_
> We have a need for [...] 

### Describe the solution you'd like
A clear and concise description of what you want to see built.

_**Example:**_
> This feature will needs to have the following requirements:
> 1. Requirement
> 2. Requirement

**Comment by grahamhency** [comment]
Hey @jaykravetz, this was already addressed. With the release of `v1.5.0` you will be able to achieve this design. See this PR for the code changes: #379
