### ISSUE TITLE
[Chore] Update Documentation for Select

### ISSUE THREAD

**Issue by escharna** [mobi/goponents#432]
### What general chore or task would you like to see performed?
https://tangoe.design/ui-kit/forms/select under component control, it is referencing text area but should reference select

###### Example 
<img width="1159" alt="Screen Shot 2020-01-31 at 1 52 05 PM" src="https://user-images.githubusercontent.com/6865003/73567651-ca39df80-4434-11ea-91e4-6edc32819e93.png">

**Comment by grahamhency** [comment]
Closed with #437
