### ISSUE TITLE
[Chore] Modify Icon Button Hover Background to Work Well Light Icon Colors

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#434]
### What general chore or task would you like to see performed?
Currently the hover state of the `go-icon-button` does not look great when the icon has a white text color (e.g. when used in a dark themed context).

<img width="286" alt="Screen Shot 2020-01-31 at 5 10 10 PM" src="https://user-images.githubusercontent.com/23343417/73577994-8e127900-444c-11ea-9724-c0ac1028153e.png">

###### Example 
We should modify the hover state of the `go-icon-button` so that it will work well for both dark and light icon colors.

This will probably be best achieved by using a darker gray for the background color but with partial opacity.

**Comment by grahamhency** [comment]
Closed with #438
