### ISSUE TITLE
[Feature] Add Select All Button to GoSelect

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#439]
### What is the feature that you would like to propose?
We have a need to add the ability to select all of the options for a `go-select` with a single click.

### Describe the solution you'd like
We should add a 'Select All' button to the `go-select` which, when clicked, selects all of the items passed into the select. This button should only appear if the `multiple` binding is set to `true`.

**Comment by grahamhency** [comment]
Closed with #440
