### ISSUE TITLE
[BUG] Table does not sort properly when there are undefined values

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#450]
**Describe the bug**
When the column you are sorting by contains undefined values, the sort behavior is incorrect. This is because comparing a string to `undefined` will always return false, [sort the sort method will return 0](https://github.com/mobi/goponents/blob/c0168b4b499f1705076181b1a521afc1553b9a34/projects/go-lib/src/lib/components/go-table/go-table-utils.ts#L23), leaving the element in its place.

**To Reproduce**
1. Create a table with some rows having undefined in a sortable column.
2. Attempt to sort the column.
3. Alas, the rows with undefined will just stay in the original place in table.

**Expected behavior**
`undefined` should be treated like empty strings, which the sort method will sort appropriately, as it's comparing string to string.

**Screenshots**
<img width="1120" alt="Tangoe Design System 2020-02-05 12-38-46" src="https://user-images.githubusercontent.com/5261826/73867317-7c4a2080-4814-11ea-89b3-3ac12d61de5d.png">

**Comment by eligolding** [comment]
This can be assigned to me.

**Comment by grahamhency** [comment]
Closed with #451
