### ISSUE TITLE
[BUG] ng-select Dropdown is slightly off on modals

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#452]
**Describe the bug**
When a select is being used within a modal, the dropdown menu underneath the input is slightly off to left.

**To Reproduce**
1. Go to a modal with an ng-select element.
2. Click on select box.

**Expected behavior**
The dropdown menu should be directly below the input.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/73874077-d7821000-4820-11ea-9af5-cde1be5b1aa9.png)

**Comment by eligolding** [comment]
This issue is related to the need to add `appendTo="body"`. It was [reported in ng-select](https://github.com/ng-select/ng-select/issues/929), and the supposed solution is to [make sure you set `position: relative` on the body](https://github.com/ng-select/ng-select/issues/929#issuecomment-437325776). I tried that and it still did not work.

You can see [my comment here](https://github.com/mobi/goponents/pull/260#issuecomment-579368883) that we might not need appendTo after all, so this issue will go away.

**Comment by grahamhency** [comment]
Closed with #452

**Comment by IoSono000** [comment]
Hi, i continue to have the same problem. If I insert the component in a simple html page no problem, but if I insert it in a more complex context, the problem remains ...

**Comment by grahamhency** [comment]
@IoSono000 can you provide an example? What version of Goponents are you running?

**Comment by IoSono000** [comment]
> @IoSono000 can you provide an example? What version of Goponents are you running?

Hi, the version is last (3.7.3).


<div class="overflow-box" style="width: 300px;">
  <ng-select [items]="tipologiaList"
            bindLabel="company"
            placeholder="Select item"
            appendTo="body"
            multiple="true"
            [closeOnSelect]="false"
            [(ngModel)]="selected2">
  </ng-select>
</div>

<div class="container">
  
  <div class="row">
    <div class="col-12 col-md-12 col-lg-12 col-xl-12">

      <form aria-labelledby="dati-ispezione" [formGroup]="intermediarioSrcForm" class="form-horizontal mt-3" novalidate>

        <div class="row">
          
          <div class="col-md-12">
            <div class="form-group">

              <label for="tipologia" translate>HOME.SEARCH_ADV.LBL_TIPOLOGIA</label>
			
			  
              <ng-select 
                appendTo="body"
                class="ng-select-custom-big" 
                labelForId="tipologia" 
                [items]="profiliRischio"
                [multiple]="true"
                [hideSelected]="true"
                [closeOnSelect]="false"
                formControlName="tipologia">
              </ng-select>
            </div>
          </div>

        </div>

      </form>
      
    </div>
  </div>

</div>

**Comment by grahamhency** [comment]
@IoSono000 that is not using the `go-select`. If you're looking for the documentation on `ng-select` you'll want to check https://github.com/ng-select/ng-select

**Comment by IoSono000** [comment]
> @IoSono000 that is not using the `go-select`. If you're looking for the documentation on `ng-select` you'll want to check https://github.com/ng-select/ng-select

sorry but your note is not clear. The implementation was done as per documentation.

**Comment by grahamhency** [comment]
@IoSono000 this repo is not the `ng-select` project. We implement the `ng-select` component in this project for our `go-select`. If you're trying to troubleshoot an issue with `ng-select` then you'll need to look at their [documentation](https://github.com/ng-select/ng-select).

If you are trying to use our Goponents library then you need to be using `go-select` here.

**Comment by IoSono000** [comment]
> @IoSono000 this repo is not the `ng-select` project. We implement the `ng-select` component in this project for our `go-select`. If you're trying to troubleshoot an issue with `ng-select` then you'll need to look at their [documentation](https://github.com/ng-select/ng-select).
> 
> If you are trying to use our Goponents library then you need to be using `go-select` here.

Ok, thanks and sorry

**Comment by renanramos** [comment]
Hi @IoSono000 
Have you found a solution for that? I've looking for a way to handle but unfortunately, I didn't find anything yet :/

**Comment by grahamhency** [comment]
@renanramos this is not the `ng-select` repo so this issue probably doesn't apply to you. However, we implemented a solution through CSS. It is messy, but it works for us.
```
// overrides incorrect alignment when appendTo body is applied to an ng-select
body > .ng-dropdown-panel {
  margin-left: 4px;
}
```

**Comment by IoSono000** [comment]
> @renanramos this is not the `ng-select` repo so this issue probably doesn't apply to you. However, we implemented a solution through CSS. It is messy, but it works for us.
> 
> ```
> // overrides incorrect alignment when appendTo body is applied to an ng-select
> body > .ng-dropdown-panel {
>   margin-left: 4px;
> }
> ```

Thanks, i added the following statement to the scss file
:: ng-deep ng-dropdown-panel {
   margin-left: 9px;
}

the problem is that if I resize the page that left margin is no longer good and it is misaligned again ... have you done this test?

**Comment by grahamhency** [comment]
@IoSono000 we have not handled that case yet.

**Comment by renanramos** [comment]
@grahamhency Thanks!
I'll use this approach in my case.
