### ISSUE TITLE
[BUG] Datepicker not saving in input.

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#458]
**Describe the bug**
When a user selects a date with the datepicker component and saves that information, when the user returns to the page to edit, the datepicker input field is empty. 

**To Reproduce**
1. Go to a form with a datepicker component: https://cloud-dev.prod.tangoe.com/employees/4346500
2. Select a Hire Date using the datepicker component.
3. Save the Employee.
4. Go back to the Employee
4. See that the Hire Date field is now empty.

**Expected behavior**
The date should be populated within the input field.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/73944718-0d76d100-48c1-11ea-9b86-fc7eb1d7aa29.png)

**Comment by grahamhency** [comment]
It seems like this is an issue of implementation. I would direct the devs building this to the component's documentation example that shows this working:

https://tangoe.design/ui-kit/forms/datepicker#form-input-control

I am going to close this issue, if they have issues getting this to work after following the docs then please have them comment on this issue.
