### ISSUE TITLE
[Chore] Update to Angular 8

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#466]
### What general chore or task would you like to see performed?
We need to update to at least Angular 8 in order for this library to be compatible with app that are using Angular 9.

### Are there any specific steps you would like completed?
1. Perform `ng update`
2. Fix all the `@ViewChild[ren]` and `@ContentChild[ren]` to have the proper `static` option.

**Comment by grahamhency** [comment]
Closed with #590
