### ISSUE TITLE
[Chore] ng-select inputs are not the same height as other inputs

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#470]
### What general chore or task would you like to see performed?
Select boxes currently have a height of 40px while other inputs are all set to 36px. The font-size declared within the ng-selects is set to 1rem while the other inputs are set to .875 rem. 

We have also noticed that some of the inputs are being cut off by the select box: 
![image](https://user-images.githubusercontent.com/8883257/74344544-cb470700-4d7a-11ea-8eef-fb305ace8ca9.png)

**Comment by grahamhency** [comment]
Closed with #471
