### ISSUE TITLE
[BUG] Modal Height Goes Beyond the Screen at Smaller Resolutions

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#476]
**Describe the bug**
When a modal becomes too long for a screen with a smaller resolution, the modal goes beyond the screen and creates extra whitespace when closed. 

**To Reproduce**
1. Go to https://cloud-dev.prod.tangoe.com/locations/123500 at 1300x600 resolution.
2. Click on the Plus Icon on Location Addresses. 
3. Hit the Add Button and get a Validation Error.
4. You will see the top of the modal is cut off and it scrolls down below the container. 
5. When you close the modal, you have that extra white space still on the page. 

**Expected behavior**
The modal should scroll inside or the modal overlay should adjust to the height of the modal. Possible breakpoints may be needed for this common resolution in Bangalore and 13 inch Windows laptop screens. max-height:100% on the go-modal__container-xl class creates an interior scroll for the modal which relieves the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/74446645-36114480-4e46-11ea-82a9-5c2c56c166e6.png)
![image](https://user-images.githubusercontent.com/8883257/74446655-3a3d6200-4e46-11ea-8536-d57d9c400235.png)
![image](https://user-images.githubusercontent.com/8883257/74446687-44f7f700-4e46-11ea-9c7d-d7ae0393313f.png)

**Comment by grahamhency** [comment]
@Fagiolia1 thanks for the thoroughly detailed issue! I've got a PR up for the fix.

**Comment by grahamhency** [comment]
Closed with #477
