### ISSUE TITLE
[Chore] Add an "x" to clear Table Search

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#480]
### What general chore or task would you like to see performed?
UX would like an X icon to clear a search inside of a table after text is entered. This icon can function exactly like the ng-select component's clear.

### Are there any specific steps you would like completed?
_Insert a list of requirements or recommendations._
1. A user searches an item on a table.
2. After they search and get their results, the user wants to perform another search.
3. Instead of requiring the user to select all and delete their previous search, give the user an option to clear the field with an x.

**Comment by grahamhency** [comment]
Closed with #484
