### ISSUE TITLE
[BUG] Left Navigation Padding Overflows Menu on Scroll

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#481]
**Describe the bug**
When a user scrolls the left navigation, the padding-top of 2rem overflows onto the menu. Instead of having this padding on the menu itself, this padding should be on the first element in the navigation.

**To Reproduce**
1. Go to tangoe.design
2. Click on the Components menu.
3. Scroll the left navigation down slightly.

**Expected behavior**
The padding should not be apart of the navigation menu itself but should be applied to the first item in the navigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/74561946-a9df4a00-4f37-11ea-9ef4-c11921d3493c.png)

**Comment by grahamhency** [comment]
Closed with #483
