### ISSUE TITLE
[Feature] Fixed Height Tables in Modals

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#482]
### What is the feature that you would like to propose?
We would like to fix the height of the tables within the modals. Currently the tables within modals are too large for the modal container on certain screen sizes (most notably 1366 x 768). This causes the modal to always scroll horizontally.

Ideally we'd like to set a max-height to the table in the modal and have the column headers freeze so the user can scroll the table itself and the entire modal's height isn't taken up by the table.  

Currently, Amit has produced this using some simple CSS in the Cloud Product. This was a necessity for the tables involved and the screen sizes of the laptops being used for QA and Dev.  

You can see an example of his code in the following pages:
1. Go to https://cloud-dev.prod.tangoe.com/employees/4346500.
2. Select the + icon next to the Assigned Cost Center Accordion.
3. Here you can see the table with a set max-height as well  as the column headers being frozen.

So while this works okay right now, if I'm viewing this on my screen the table height is a little small. There may be a need for some breakpoints or media queries for smaller screen sizes to alleviate this.

**Comment by grahamhency** [comment]
Closed with #484
