### ISSUE TITLE
[BUG] Dynamically Creating Radio Buttons

### ISSUE THREAD

**Issue by andrewariley87** [mobi/goponents#488]
**Describe the bug**
When iterating through an array to dynamically create a `go-radio-button` you get  the following error:

<img width="543" alt="Screen Shot 2020-02-18 at 1 12 15 PM" src="https://user-images.githubusercontent.com/12799112/74768648-f045e900-5256-11ea-97a8-dd858e9b19ce.png">

**To Reproduce**
Here is some example code to recreate the problem:

```
<go-radio-group 
  legend="Authentication Strategies"
  [control]="businessForm.get('authentication_strategy')" >
  <go-radio-button
    [label]="strategy"
    [formValue]="strategy"
    *ngFor="let strategy of authenticationStrategies">
  </go-radio-button>
</go-radio-group>
```

**Expected behavior**
Should be able to iterate through an array to dynamically create radio buttons

**Comment by grahamhency** [comment]
Closed with #489
