### ISSUE TITLE
[BUG] Add the option to disable Select All on multi-select inputs

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#495]
**Describe the bug**
We would like the option to turn the Select All button off on a multi-select input. Currently the Select All button appears by default and is causing issues when there are many records in a multi-select.

![image](https://user-images.githubusercontent.com/8883257/75266999-2cca9500-57c1-11ea-99cd-8b27c297b7d7.png)

**Comment by grahamhency** [comment]
Closed with #499
