### ISSUE TITLE
[Chore] Increase .go-tab__header padding to 1rem

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#502]
### What general chore or task would you like to see performed?
Currently the .go-tab__header padding is set to .5rem, 1rem. This should be changed to 1rem, 1rem to give the tab headers a bit more breathing room.

**Comment by grahamhency** [comment]
@Fagiolia1 this is as easy change, but what do you think about doing `.75rem 1rem`? Decreases the vertical height by `.5rem`, but still provides better spacing. Thoughts?

**Comment by Fagiolia1** [comment]
@grahamhency .75rem works for me!

**Comment by grahamhency** [comment]
Closed with #506
