### ISSUE TITLE
[Chore] Align Left Navigation Colors with DSM

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#510]
### What general chore or task would you like to see performed?
Currently the grays being used in the left navigation in go-ponents is a bit off from the grays defined in the DSM. We would like the left navigation colors to be aligned with the rules outlined in the DSM: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3dbcd5fbc24436f4bae8c

This also includes the App Drawer menu at the bottom.

**Comment by grahamhency** [comment]
This is a duplicate of #414, going to close.
