### ISSUE TITLE
[BUG] go-side-nav accordions with same routeTitle open simultaneously

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#512]
**Describe the bug**
When clicking a NavGroup item within a `go-side-nav`, if there are other NavGroups with the same `routeTitle`, those accordions will be expanded in addition to the one that was clicked.

**To Reproduce**
1. Implement a `go-side-nav` which has multiple NavGroups with the same `routeTitle`.
2. Click on one of those NavGroups.

**Expected behavior**
Clicking a NavGroup should not cause other NavGroups with the same `routeTitle` to expand.

**Screenshots**
Here multiple NavGroups have a `routeTitle` of `'Carriers'`, and so clicking one of them opens or expands the other two:
<img width="257" alt="Screen Shot 2020-03-17 at 4 05 52 PM" src="https://user-images.githubusercontent.com/23343417/76896938-3186e400-6869-11ea-9473-fed08ea0c0ba.png">

**Comment by grahamhency** [comment]
Closed with #513
