### ISSUE TITLE
[BUG] Action Sheets not closing when user clicks.

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#514]
**Describe the bug**
When a user clicks on a link in an action sheet component, the action sheet is not closing. 

**To Reproduce**
1. Go to an Action Menu
2. Click on an action within that menu.
3. Menu remains open.

**Expected behavior**
The menu should close once the user clicks on an action.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/76974407-8b3deb80-6907-11ea-9b3c-91a42b8b44b7.png)
![image](https://user-images.githubusercontent.com/8883257/76974435-955fea00-6907-11ea-9d24-ab8462dfa53f.png)

**Comment by grahamhency** [comment]
Closed with #521
