### ISSUE TITLE
[Feature] Add custom attributes input to go-side-nav

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#515]
### What is the feature that you would like to propose?
There will be cases where we need all of the `menuItems` of a `go-side-nav` to have some custom attribute applied to them. For example, for Tangoe Mobile we need the all of the main side nav menu items to have a `walkme` attribute. We do not want to add a specific `walkme` input to `go-nav-group` or `go-nav-item`, because this is a very specific use case. 

### Describe the solution you'd like
We should be able to pass in the names of any attributes we want to be added to each menu item.

**Comment by grahamhency** [comment]
Closed with #526
