### ISSUE TITLE
[BUG] Slim Accordion Can't Remove Content Padding

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#516]
**Describe the bug**
When using the go accordion there is a bug with using the bindings slim and removeContentPadding together. We're using slim to reduce the font size and padding of the header, but we also want to remove the padding from the content as the content is a list of buttons that should take up the full width of the accordion. 

**To Reproduce**
1. Add an accordion with `[slim]="true"`
2. Add an accordion panel underneath the accordion that has `[removeContentPadding]=true`
```
<go-accordion [slim]="true">
  <go-accordion-panel [removeContentPadding]="true">
    Some Text Here
  </go-accordion-panel
</go-accordion>
```

**Expected behavior**
I would expect the above setup to remove the padding around the accordion panel, but as you see in the pictures, the styles for removing the padding are being overwritten by the slim property

**Screenshots**
<img width="299" alt="Screen Shot 2020-03-18 at 11 32 08 AM" src="https://user-images.githubusercontent.com/17074863/76978372-fc33d200-690c-11ea-9f17-57c34cdbae8e.png">
<img width="313" alt="Screen Shot 2020-03-18 at 11 32 59 AM" src="https://user-images.githubusercontent.com/17074863/76978389-ffc75900-690c-11ea-8351-f83e4bf025ef.png">

**Comment by grahamhency** [comment]
Closed with #527
