### ISSUE TITLE
[BUG] Copy Button Text Area Tabable

### ISSUE THREAD

**Issue by StevenUlmer** [mobi/goponents#517]
**Describe the bug**
A user can tab to the text area that stores the text for the copy button

**To Reproduce**
1. Go to 'https://tangoe.design/ui-kit/copy'
2. Press tab a couple times. You will tab off the screen to a far away text area

**Expected behavior**
A user should not be able to tab to the copy text area

**Comment by grahamhency** [comment]
Closed with #522
