### ISSUE TITLE
[Feature] Custom Table Headers

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#519]
### What is the feature that you would like to propose?
We would like the ability to customize table headers a bit more.  

_**Example:**_
We have a need for some table headers to be go-heading-4s  instead of go-heading-3s since these tables appear within cards.

We also have a need to have the table headers function as a ng-select menu where the user can toggle  through multiple tables in a single accordion.

### Describe the solution you'd like
We would like the ability in go-ponents to customize the table-header element a bit more. These customizations include replacing the title with a ng-select menu or changing the header size.

_**Example:**_
You can see an example of the select menu being used as a table-header in the following example:
https://tangoe.invisionapp.com/share/URUHTZLWFQS#/396747554_Invoice_Detail

Scroll down to View By and you can see an example of this.

**Comment by grahamhency** [comment]
@Fagiolia1 We can look at providing a content projection slot for the title area, but in the meantime there is somewhat a workaround for this.

If you do not apply a `tableTitle`, set `[renderBoxShadows]="false"`, and don't pass in table actions inside of the table, then you effectively can achieve the layout shown in the mockup by adding a div above the table and positioning the elements appropriately. Something like:
```html
<div>
  <go-select></go-select>
  <ul class="go-button-group">
    <li class="go-button-group__item">
      <go-icon-button buttonIcon="apps"></go-icon-button>
    </li>
  </ul>
</div>
<go-table
    [tableConfig]="tableConfig"
    [renderBoxShadows]="false">
    <go-table-column field="id" title="ID"></go-table-column>
    <go-table-column field="name.first" title="First Name"></go-table-column>
    <go-table-column field="name.last" title="Last Name"></go-table-column>
    <go-table-column field="email" title="Email"></go-table-column>
    <go-table-column field="gender" title="Gender"></go-table-column>
    <go-table-column field="ip_address" title="IP Address"></go-table-column>
  </go-table>
```

**Comment by Fagiolia1** [comment]
Thanks @grahamhency ! Will pass this along to Jay.
