### ISSUE TITLE
GoToasterService Wording

### ISSUE THREAD

**Issue by mwagz** [mobi/goponents#52]
Purely a question, but currently, the GoToasterService has a `toastSuccess` and a `toastError` method in it. This works absolutely fine, as long as we continue to use a toast as our primary way of delivering information to the user.

Would it be better for these methods to be simplified to `success` and `error`? This would allow the implementation to always remain the same, even if we switch away from GoToasterService, so long as the method of delivering information to the user has a `success` and `error` message.

**Comment by AlexOverbeck** [comment]
I wouldn't be opposed this. I can bring this question up to our community next time we meet. We would need to deprecate the previous usage and work it out gradually to prevent breaking changes.

My only opposition here is that the "toaster" terminology will still remain. If we wanted to make the service more generic we could consider moving back towards the "messaging" terminology. I'd maybe consider that _too_ generic though.

**Comment by mwagz** [comment]
Moving back towards the "Messaging" terminology, as @grahamhency mentioned before, creates an issue around if we ever decide to create an actual instant messaging service.

**Comment by AlexOverbeck** [comment]
Seems like there isn't a clear best way to go here. If this is an issue that needs addressed in the future we can reassess.
