### ISSUE TITLE
[Feature] Horizontal Rule

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#520]
### What is the feature that you would like to propose?
We would like a horizontal rule component that can be used to break up cards.

### Describe the solution you'd like

1px solid #F0F0F0
1 rem of space above and below.

Should stretch to 100% of the card, if possible.
_**Example:**_
Here is an example of the HR being used in a card:
https://tangoe.invisionapp.com/share/URUHTZLWFQS#/396747554_Invoice_Detail

**Comment by kpmurphh** [comment]
Documentation can be found here: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5e74f5132834ca567f3ef8d5

**Comment by grahamhency** [comment]
Closed with #545
