### ISSUE TITLE
[CHORE] Add positive, negative, and neutral options to go-icon's iconModifier input

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#525]
### What general chore or task would you like to see performed?
Currently the `iconModifier` input of `go-icon` accepts only `'light'` and `'dark'` as inputs (which set the icon's color to white and black), respectively. We should add the ability to pass in `'positive'`(green), `'negative'` (red), and `'neutral'` (purple).

One instance where this would be useful is for setting the colors of the checkmark and 'X' icons that appear in Tangoe Mobile's tables to green and red, respectively.

**Comment by grahamhency** [comment]
Closed with #537
