### ISSUE TITLE
[Feature] Full Screen Mode for iframes

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#529]
### What is the feature that you would like to propose?
We would like the ability to expand the Sisense Dashboard iframe to a full screen view. This view would have all of the features of the current iframe view. If the user navigates to a different report or drills into a report, when the user closes the full screen, the page should reflect this.

The user would enter full screen mode by clicking on the fullscreen icon in the top right corner of the dashboard page. This would expand the iframe to a full screen view with selectors to change dashboards.

_**Example:**_
https://tangoe.invisionapp.com/share/URUHTZLWFQS#/411729583_Alternate_Dashboard

**Comment by grahamhency** [comment]
@Fagiolia1 I have two comments about this.

1. I think this feature is outside of the scope of Goponents.

2. I actually think we're moving away from embedding Sisense iframes into the app. Check with Jason or maybe @patryk0605 for more info on that.

**Comment by Fagiolia1** [comment]
I spoke with @patryk0605 and @eligolding about this a few weeks back. I believe Patrick's concept with Sisense mimicking the Tangoe platform really only works for the Analytics app. Since we have dashboards within the Cloud application, I think there is still a need for this treatment.

**Comment by grahamhency** [comment]
@Fagiolia1 okay, that's fine. However, I still think this is something outside the scope of Goponents.
