### ISSUE TITLE
GoTableColumn Doesn't Handle Undefined Field/Title

### ISSUE THREAD

**Issue by mwagz** [mobi/goponents#53]
The GoTableColumn leverages the [`go-table-utils` method `extractFieldData`](https://github.com/mobi/goponents/blob/master/projects/go-lib/src/lib/components/go-table/go-table-utils.ts#L1):

```typescript
export function extractFieldData(key: string, obj: object) {
  return key.split('.').reduce((p,c) => p && p[c], obj);
}
```

If the user implements a column that doesn't have iterable data (a column containing only icons, for example), then omitting the field and data on the GoTableColumn calls the `getFieldData` method, which then calls the method above, `extractFieldData`.

Executing `split` on `undefined` will throw an error.

**Comment by AlexOverbeck** [comment]
This seems like a valid issue. @mwagz we are expecting a release to go out no later than July 31st. Can this fix be rolled into that version or would you rather a hot fix?

**Comment by mwagz** [comment]
> This seems like a valid issue. @mwagz we are expecting a release to go out no later than July 31st. Can this fix be rolled into that version or would you rather a hot fix?

I think that would suffice.

**Comment by AlexOverbeck** [comment]
@mwagz We will make sure that this bug is resolved as a part of the next version. You can monitor progress of this issue here: https://github.com/mobi/goponents/projects/1
