### ISSUE TITLE
[BUG] Data Table Sort Arrow slightly off

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#530]
**Describe the bug**
The up and down arrows on the data table used to sort are slightly off-center from the table headers.

**To Reproduce**
1. Go to a data table.
2. Click on a column
3. See error

**Expected behavior**
The arrows should be on the same line as the table headers.

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/78257576-0981bc80-74c8-11ea-954d-40d2c37cb1be.png)
![image](https://user-images.githubusercontent.com/8883257/78257588-10a8ca80-74c8-11ea-8ead-9f8810115886.png)

**Comment by grahamhency** [comment]
Closed with #532
