### ISSUE TITLE
[Chore] Header Bar Adjustments

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#539]
### What general chore or task would you like to see performed?
On the header bar with the back arrow, can we make the following adjustments:

- Can we have the line that separates the arrow space from the header space align with the left side? That way it's always lined up with the header or the card below. See image for example. The arrow should remain centered like in the example.
- The arrow size should be 16px/1rem (currently 18px).
- The line color should be #D3D3D3 (currently #B1).

###### Example 
<img width="697" alt="Screen Shot 2020-04-24 at 12 03 13 PM" src="https://user-images.githubusercontent.com/9440696/80232862-96311d80-8623-11ea-8db5-6a9733d07bee.png">

**Comment by grahamhency** [comment]
Closed with #569
