### ISSUE TITLE
[BUG] Console error when adding attributes to go-nav-items

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#540]
**Describe the bug**
If there are any `go-nav-item`s in the `menuItems` passed into `go-side-nav` which have custom attributes specified (via adding an `attributes` property), a `Cannot read property 'nativeElement' of undefined` error is thrown and those nav-items fail to render correctly.

For some reason this does not appear to occur with the go-style-guide or go-tester, but does occur when implementing a `go-side-nav` in the Tangoe angular app.

**To Reproduce**
1. Implement a GoSideNav with one or more of the nav-items included in the array passed to its `menuItems` input having `attributes` specified.
4. Open dev tools to see error.

**Expected behavior**
There should be no errors resulting from adding attributes to `go-nav-item`s. 

**Screenshots**
![Screen Shot 2020-04-27 at 2 33 29 PM](https://user-images.githubusercontent.com/23343417/80407809-32615b80-8894-11ea-936f-88567927ab15.png)

![Screen Shot 2020-04-27 at 2 33 08 PM](https://user-images.githubusercontent.com/23343417/80407784-283f5d00-8894-11ea-9d5c-8480a912c980.png)

**Comment by grahamhency** [comment]
Closed with #541
