### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#542]
Go Accordion component panel heading to allow hyperlinks. 

We have a requirement to show a hyperlink in the accordion panel header. At present heading input variable takes only string.

Suggestion: Provide two input variables. A boolean input variable to specify if the header should be an hyperlink or not. Second one to accept the href or routerLink as string. If both are provided render an anchor tag instead of span. 

<img width="767" alt="Accordion" src="https://user-images.githubusercontent.com/4224079/80590407-717ce180-8a39-11ea-9802-fc9abdc24064.PNG">

**Comment by grahamhency** [comment]
@sudheepdivakargithub, see the "Header Template" section on the [Accordion Panel Docs](https://tangoe.design/ui-kit/accordion/panel). I believe this should suffice as a solution.
