### ISSUE TITLE
[Chore] Enhanced Functionality For GoSelect

### ISSUE THREAD

**Issue by stolve** [mobi/goponents#549]
UX would like the GoSelect component to be enhanced to handle the following usages:

**Normal Select**
Default HTML type select functionality (e.g. click to dropdown list of options and select one - no search)

**Standard Autocomplete**
Turning off manual dropdown and only have search capability in cases where there are large quantities (e.g. searching locations from the database)

**Lazy Loading**
If possible, we would also like to explore the idea of lazy loading large datasets that use the manual dropdown of the select, loading in a set number of results and then loading in more as the user would scroll.

**Comment by grahamhency** [comment]
Thanks for submitting this @stolve.

I believe the "Normal Select" is already achievable, but requires some specific bindings to be applied. 

For the "Autocomplete", we would have to explore that a bit. Certainly doable. 

For "Lazy Loading", we would need to build out a precursor for this. Some sort of infinite/virtual scrolling component/directive to be used in this. I can follow up and create an issue for that.

**Comment by StevenUlmer** [comment]
@stolve, @grahamhency I believe the "Autocomplete" functionality already works and is built out. It's listed under Typeahead here https://tangoe.design/ui-kit/forms/select

For the normal select the documentation is under Search and can be toggled through the ` `[searchable]="false"` binding

**Comment by grahamhency** [comment]
Thanks @StevenUlmer, I think the key part in the "Autocomplete" functionality is that they don't want the drop down portion to appear until there are results to show. Right now, it appears when you focus on the element.

**Comment by kpmurphh** [comment]
hey @grahamhency can we discuss this on our next UX/UI call? mainly leaving this comment so I don't forget.

**Comment by grahamhency** [comment]
@kpmurphh we can, yeah. Might be worth just working through the different options already available to us and see if we can achieve the different states @mobi/tangoe-ux-ui is looking for.

**Comment by grahamhency** [comment]
Work done for this issue will be for the documentation of the UX patterns for go-selects in our applications. These issues must be closed for us to be able to implement the documentation of these patterns:
- #634 
- #635 
- #636
