### ISSUE TITLE
[BUG] Table search term does not get set if passed in later

### ISSUE THREAD

**Issue by eligolding** [mobi/goponents#551]
**Describe the bug**
If you set the searchTerm on the `GoTableSearchConfig` after the table was already instantiated, it will not get set as the value in the search input on the table.

**To Reproduce**
1. Create a go-table with a tableConfig that does not contain a search term.
2. Update the tableConfig and set `searchTerm`
3. Look at the rendered table and be sad about the fact that your searchTerm is not there.

**Expected behavior**
As explained in the docs, the use case for using this property is when implementing server side integration. In my case I am also doing deep linking. As the user types into the searchbar, I add the searchTerm to the url. When the user refreshes the page, since the searchTerm is in the url it will be used for filtering the data. However, because of this bug, it is not being shown as the value in the searchbar, which is just confusing because the data will still be filtered.

**Screenshots**
<img width="1039" alt="Tangoe 2020-05-13 17-46-07" src="https://user-images.githubusercontent.com/5261826/81869266-be84ab80-9541-11ea-9760-8eef737bd91c.png">

**Comment by grahamhency** [comment]
Closed with #552
