### ISSUE TITLE
[Chore] Left Navigation Top Link Adjustment

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#560]
### What general chore or task would you like to see performed?
When selecting the top navigation link in the side navigation, there is 10px of extra space that remains the original color of the side nav. We would prefer if this padding was a part of the first link and also changed color when being hovered/selected. Please see screenshots for reference.

Currently how it is:
<img width="134" alt="Screen Shot 2020-05-26 at 1 42 40 PM" src="https://user-images.githubusercontent.com/9440696/83069805-7fbe1d80-a038-11ea-8add-bf958dcaf27a.png">

What we want to happen (this example doesn't have the active green nub in it, please disregard that! That green nub isn't changing!):
<img width="259" alt="Screen Shot 2020-05-26 at 1 42 19 PM" src="https://user-images.githubusercontent.com/9440696/83069809-8187e100-a038-11ea-98af-3c78b075855f.png">

**Comment by grahamhency** [comment]
Closed with #565
