### ISSUE TITLE
[Chore] Update Select Dropdown Stylings

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#575]
### What general chore or task would you like to see performed?
Please make the following styling changes to the select control dropdown:

- The dropdown items font size should be 14px/.875rem, they are currently 16px/1rem.
- The hover for the selected item in a dropdown background color should be #FFFFFF darkened 3.5% and the selected should be Roboto Light (currently Medium when selected) and should have a background color of #FFFFFF darkened 7% (I put that [here](https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5e30a4a8ad74743e4cda83b0) in the DSM)
- Can we change the "Select All" button/section to look like [this](https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/asset/components/5e666493d784ab7e059176dd)? Currently it is/looks like a button. It should look like a dropdown item and there should just be a separator between it and the other options.

**Comment by grahamhency** [comment]
@kpmurphh, can you clarify this point?

> The hover for the selected item in a dropdown background color should be #FFFFFF darkened 3.5% and the selected should be Roboto Light (currently Medium when selected) and should have a background color of #FFFFFF darkened 7% (I put that here in the DSM)
