### ISSUE TITLE
File upload section should be reset after uploading a file

### ISSUE THREAD

**Issue by amitpatra91** [mobi/goponents#577]
**Describe the bug**
File upload section should be reset after uploading a file.

**To Reproduce**
1. Go to ' Forms->File upload'
2. Drag and drop file upload section should be reset after uploading a file

**Expected behavior**
It should allow the user to upload the same file again. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33975358/84026044-3790ea80-a9aa-11ea-9c49-fb26d15067e9.png)

**Comment by StevenUlmer** [comment]
@amitpatra91 did you use the `[multiple]="true"` attribute here? That should allow it to upload multiple files instead of just one.

**Comment by amitpatra91** [comment]
Yes. I have used that [multiple]="true". But after clear the file below close icon. I can't upload the same name file. And also I want after upload the file will call one api and then want to reset every thing in upload section in my application.

**Comment by grahamhency** [comment]
@amitpatra91 so it sounds like you're requesting a couple things here:

1. If the file upload is not set to `multiple="true"`, if a new file is drag/dropped onto the file upload, then it should replace the current uploaded file
2. You would like the ability to manually reset the file upload to it's original state
3. You want the ability to know when a file has been uploaded

Do these sound right?

**Comment by amitpatra91** [comment]
I have checked in design system page where couldn't be able to upload the same file more than once.
