### ISSUE TITLE
[Chore] Side Navigation Changes

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#584]
### What general chore or task would you like to see performed?
Please adjust the following in the side navigation:

**Icon Sizes**
- Standard left side icon should be 16px/1rem (small icon size), currently is 19.2px
- App Drawer icon should be 24px/1.5rem (large icon size), currently is 20px

**Links**
- The "Active" link font weight is currently 700 (Nunito bold) and we want it to be 600 (Nunito semi-bold).

**Comment by jaredami** [comment]
Hey @kpmurphh just had a couple questions on this:

**First:** Is the documentation out of date here? https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5c9435edae717d314c2b0c69

In the "App Drawer" section is says both the font and icon sizes should be 20px/1.25rem. Is that correct?

If not, should _only_ the icons in the app drawer be changed to 1.5 rem, or should the text font-size be changed to that as well?

**Second:** Would mind pointing me to specifically where you are seeing a font-weight of 700 in the side nav? It looks to me that the active nav items have a font-weight of 400 and the inactive ones are 300 (see below). I'm probably misunderstanding what you're referring to by "Active link".

![Screen Shot 2020-06-25 at 1 20 50 PM](https://user-images.githubusercontent.com/23343417/85768190-c447e200-b6e6-11ea-9fd8-6a902cb183e1.png)

![Screen Shot 2020-06-25 at 1 23 43 PM](https://user-images.githubusercontent.com/23343417/85768537-2274c500-b6e7-11ea-8eab-7f5893eae466.png)

Thanks!

**Comment by grahamhency** [comment]
Hey @kpmurphh, I want to clarify something. Can I make a recommendation against using the `600` font weight or switch to using `600` instead of `700`? The main reason here is that we need to import different variations of the fonts. Each additional font we import is additional load for the user.

**Comment by kpmurphh** [comment]
> In the "App Drawer" section is says both the font and icon sizes should be 20px/1.25rem. Is that correct?
> If not, should only the icons in the app drawer be changed to 1.5 rem, or should the text font-size be changed to that as well?

That is not correct. The Product icon should be 24px and the more icon should be 20px. The font size should be 20px. 

> **Second:** Would mind pointing me to specifically where you are seeing a font-weight of 700 in the side nav? It looks to me that the active nav items have a font-weight of 400 and the inactive ones are 300 (see below). I'm probably misunderstanding what you're referring to by "Active link".

I don't remember where I saw it (go figure I can't find it anymore), but regardless the font-weight of an Active link should be 600. Truthfully I can't name exactly where 700 is used in the shell, but we can switch to 600 instead of 700. Thanks!

**Comment by grahamhency** [comment]
@kpmurphh, sorry I was mistaken. I didn't mean `700`, I meant `500`. 

In our variables file, we currently have:
```
$weight-light: 300;
$weight-regular: 400;
$weight-medium: 500;
```

Where `$weight-medium` is used anywhere we need something "bold". What I was actually asking above was if we could make use of this variable (at weight 500) instead of adding the 600. I'm just trying to avoid adding a 4th font to our apps.

**Comment by jaredami** [comment]
@kpmurphh Also, by "active link" were you referring to the nav-group title ("Components" below) or the nav-item title ("Accordion" below), or both?

![Screen Shot 2020-07-07 at 10 39 21 AM](https://user-images.githubusercontent.com/23343417/86798046-5d0f2380-c03e-11ea-8bf9-8dcf96ca275b.png)

**Comment by kpmurphh** [comment]
@grahamhency 

> Where `$weight-medium` is used anywhere we need something "bold". What I was actually asking above was if we could make use of this variable (at weight 500) instead of adding the 600. I'm just trying to avoid adding a 4th font weight to our apps.

So @mobi/tangoe-ux-ui discussed and since 500 won't work since Nunito doesn't offer a 500 weight and Nunito Regular/400 isn't being used anywhere, can we replace Nunito 400 with Nunito 600? This shouldn't really affect load since removing 400 takes out 167kb and adding 600 puts in 169kb (according to Google fonts). Then, the only thing that needs to be added is an additional SASS variable if I'm not mistaken.

**Comment by kpmurphh** [comment]
> @kpmurphh Also, by "active link" were you referring to the nav-group title ("Components" below) or the nav-item title ("Accordion" below), or both? Or maybe something else entirely?
> 
> ![Screen Shot 2020-07-07 at 10 39 21 AM](https://user-images.githubusercontent.com/23343417/86798046-5d0f2380-c03e-11ea-8bf9-8dcf96ca275b.png)

Yup I'm referring to both.
