### ISSUE TITLE
[Feature] Split Button

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#602]
### What is the feature that you would like to propose?
The ability to have a button with other options behind a drop down arrow

_**Example:**_
> https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3f2c3d04745c212081590

### Describe the solution you'd like
"Under" a button, there should be the option to pass in various other options for the button.

This feature will needs to have the following requirements:
1. Current button stays as is
2. Ability to pass in other clickable options as either a button input or templates
3. Button dropdown should close after clicking an option

**Comment by grahamhency** [comment]
@mobi/tangoe-ux-ui, I have a couple questions regarding the design of this:
1. Will we ever need to pass `html` into the other options for the buttons? (including icons)
2. The dropdown should only appear if the user clicks on the arrow, correct?

**Comment by kpmurphh** [comment]
@grahamhency see comments below!

> 1. Will we ever need to pass `html` into the other options for the buttons? (including icons)
No I don't think so. We don't have a need for it currently. 

> 2. The dropdown should only appear if the user clicks on the arrow, correct?
Yes.
