### ISSUE TITLE
[Chore] Table Design Updates

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#605]
### What general chore or task would you like to see performed?
Please make the following design changes to the table:

- Table action icons should be medium (1.25rem) - currently small (1rem)
- Column header letter spacing should be 0.08px - currently 1px
**Search:**
- Search input height should be 36px, currently 32px
- There should be no box shadow on the search. Instead there should only be a border 1px solid #D3D3D3
- Upon hovering and selecting there should be a box shadow which is (the same as the global search): 0px 1px 6px 0px rgba(32,33,36,0.28);

**Comment by Ashygoyal** [comment]
The first point regarding table action icons, that is already handled. If you refer to 'buttonSize' property [here](https://tangoe.design/ui-kit/icon-button/#usage), there are 3 options provided: small (16px/1rem), medium  (20px/1.25rem), large (24px/1.50rem). The user has the flexibility to choose the size of icon buttons.

**Comment by eligolding** [comment]
@Ashygoyal agreed, that is not something that needs to be done within goponents. Users should set the `buttonSize` accordingly when passing icons into the table.

**Comment by grahamhency** [comment]
@Ashygoyal had the idea to update the documentation of the table actions to use the medium sized icons. That way we document the pattern at the very least.
