### ISSUE TITLE
go-datepicker: Need an option to provide custom date format to the component. 

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#612]
### What is the feature that you would like to propose?
At present date picker supports only two date formats (YYYY-MM-DD and MM-DD-YYYY). Provision to input custom date formats will be a value addition to the component and is required for our application.

**Comment by grahamhency** [comment]
@sudheepdivakargithub what date format is desired?

**Comment by grahamhency** [comment]
Also, @sudheepdivakargithub the `locale` input can be used to change the format based on a users locale. https://tangoe.design/ui-kit/forms/datepicker#form-input-type

**Comment by sudheepdivakargithub** [comment]
Hi Graham, 

We currently follow MMM DD, YYYY.  

Passing locale will work for us. Not sure which locale by default supports this format.

**Comment by grahamhency** [comment]
@sudheepdivakargithub this spurred a question I asked to the UX team about standardizing our date formats across the apps. I have some questions from my conversation with @mobi/tangoe-ux-ui 

- How was the `MMM DD, YYYY` format decided on?
- Is the `MMM` portion of this translated depending on locale currently?
- Would there be any resistance to changing that format (from either dev or product teams)?

**Comment by sudheepdivakargithub** [comment]
@grahamhency 
Had a discussion with PO and UX team. They will come up with a requirement to address the formatting. Hence closing the ticket.

**Comment by grahamhency** [comment]
@sudheepdivakargithub thanks for following up.
