### ISSUE TITLE
Add flexibility to the radio button to control the visibility of legend and properties in .go-form__fieldset CSS class

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#639]
By default control gives a legend , border and some padding to the radio buttons.  I think if these features are controllable it will be easy to match with the our requirements. Please find the mock-up attached for reference. 

![image-20200723-124438](https://user-images.githubusercontent.com/4224079/89252475-7b654080-d637-11ea-83c5-ba70d9a115ec.png)

**Comment by grahamhency** [comment]
To clarify on this issue, @sudheepdivakargithub, you'd like the ability to pass in a binding to the `go-radio-group` that would remove the `fieldset` and `legend` in the component so that it would only render the radio buttons?

**Comment by sudheepdivakargithub** [comment]
@grahamhency, 

I dont see any harm with the fieldset. For legend, we can add it to the DOM only if its provided. 

Problem is with the border of the fieldset. Not all designs may need it. A way to control it would be ideal.

**Comment by grahamhency** [comment]
@sudheepdivakargithub sure, perhaps I wasn't clear enough, but I just meant "remove it from view" in the UI not necessarily remove it from the html of the component. Thanks for the clarification though.
