### ISSUE TITLE
[Chore] Make disabled checkbox consistent with other form components

### ISSUE THREAD

**Issue by jaredami** [mobi/goponents#661]
### What general chore or task would you like to see performed?
We should make the way we handle disabling the `go-checkbox` consistent with the other form components.

Currently, the checkbox is disabled via its `disabled` input, but we should follow the pattern of the other form components and make it so that the checkbox is disabled simply by disabling the `FormControl` that gets passed to its `control` input.

### Are there any specific steps you would like completed?
1. Remove the component's `disabled` input.
2. Remove where we are setting the `disabled` attribute on the checkbox's hidden input.
3. Adjust the disabled styles to apply when `control.disabled` is `true`.
4. Remove the disabled section of the checkbox docs (this should no longer be necessary given that we are removing the input).

> NOTE: Solving this as suggested will constitute a breaking change.

**Comment by Ashygoyal** [comment]
When disabled, should the cursor be `not-allowed` or the current one, which is `pointer`?
@jaredami @kpmurphh @grahamhency

**Comment by grahamhency** [comment]
@Ashygoyal yep!

**Comment by Ashygoyal** [comment]
> @Ashygoyal yep!

Done, changes up in the [PR# 668](https://github.com/mobi/goponents/pull/668)
