### ISSUE TITLE
[BUG] Dark Theme on go-select

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#676]
**Describe the bug**
The `go-select` does not have appropriate styling applied when `theme="dark"` is set. The label and hints are styled correctly, but the actual `ng-select` component is not styled correctly.

**To Reproduce**
1. Create a `go-select` with `theme="dark"` set
2. See that the `ng-select` element is not styled correctly

Stackblitz Example:
https://stackblitz.com/edit/goponents-dark-go-select

**Expected behavior**
I would expect the `ng-select` element and dropdown to be styled in a way that matches the overall dark theme.

**Comment by grahamhency** [comment]
@mobi/tangoe-ux-ui can we get some design insight on this one and what it's supposed to look like? Thaaaaaaanks.

**Comment by grahamhency** [comment]
DSM for dark themed stuff (it says off-canvas, but that's where all the dark-themed stuff is) 

https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d6ecba0bbf330b5e308562c

**Comment by Ashygoyal** [comment]
@kpmurphh / @cosmicdust73 / @stolve  : As per the link provided in above comment, please confirm if we need to follow the below guidelines for dark theme on go-select.

![image](https://user-images.githubusercontent.com/3825309/97433590-c398b400-1943-11eb-8001-90668de56106.png)

**Comment by cosmicdust73** [comment]
@Ashygoyal / @grahamhency / @kpmurphh / @stolve : I would advise against following these guidelines in isolation, just for the go-select. These guidelines need to be followed 'as a whole' for all dark themed stuff. (i.e. off-canvas) If we only change go-select, we will still have the same problem where it is the only dark themed form element that looks different.

**Comment by Ashygoyal** [comment]
Thanks @cosmicdust73 ,I have updated the styles for dark versions of select dropdowns and input fields.

@grahamhency : I did not see any styles for dark version of a **radio button group**, a **datepicker**, **file upload** field and a **text area**.
When it comes to forms, I think we are supporting dark versions only for input fields and select dropdowns. 
![image](https://user-images.githubusercontent.com/3825309/97572817-d5935900-1a0e-11eb-9eaa-c323b20d99b0.png)
Please correct me if I am wrong.

Also, If we wish to include a dark version for all of the aforementioned **inputs** which we missed out, I think it should be part of a new issue/ticket. Let me know your thoughts on this.

**Comment by grahamhency** [comment]
@Ashygoyal, @mobi/tangoe-ux-ui a couple of notes:

1. @Ashygoyal, you can just reference @mobi/tangoe-ux-ui if you want to get feedback from anyone on the UX team in the future 😬  (I am also on that team)

2. The some of the other inputs have already been handled by @jaredami in #690 so I think we really just need to worry about the select here, but you may want to cross-reference them.

3. The [radio-button-group](https://tangoe.design/ui-kit/forms/radio/#form-radio-hints) and [file-upload](https://tangoe.design/ui-kit/forms/file-upload/#form-file-upload-theme) do have dark themes, but they're done through a binding. The `go-datepicker` is missing a dark them (create an issue), and the `go-text-area` has been done through the CSS cascade, but I would opt for adding a `theme` binding like we have for most of the rest of the components (this could probably be done on the `go-input` component too)

4. I agree, these should probably be done in separate pull requests at the very least.
