### ISSUE TITLE
[Chore] Missed out an attribute in one of the examples of go-toast

### ISSUE THREAD

**Issue by Ashygoyal** [mobi/goponents#677]
### What general chore or task would you like to see performed?
In the documentation for go-toast, the example titled **Basic Example** has `type' attribute missing for one of the toasts.

###### Example 
> We need to fix the aforementioned example in the documentation
![image](https://user-images.githubusercontent.com/3825309/95325490-e5f85e00-08be-11eb-942d-e479c4eb9012.png)

### Are there any specific steps you would like completed?
_Insert a list of requirements or recommendations._
1. Just include `type` attribute in the go-toast (neutral) example.

**Comment by grahamhency** [comment]
@Ashygoyal see my comment on #678, but closing this issue.
