### ISSUE TITLE
[Feature] Add New Attributes to Modal Window

### ISSUE THREAD

**Issue by cosmicdust73** [mobi/goponents#680]
1) Need ability to control the display of the 'X' in the top right corner of the modal window. (default should be on/visible)
2) Ability to control the ability to close the modal window by clicking outside of the modal (default should be off/disabled) 

UX/Product has a need to display the 'X' in some/most use cases, but also a need to hide the 'X' when displaying confirmation messages and/or Yes/No dialog windows. 

Currently, as reported by Telecom Ordering DEV team, Goponents modal windows can only be configured within the application as always displaying the 'X' or always hiding  the 'X'... and they are asking for this to be an attribute that can be passed in.

Additionally, all modal windows currently allow the user to close the window by clicking outside of it. UX does not want this to be the default behavior, but instead an option that can be passed in for the rare cases where this behavior is desired. (i.e. for modal windows that are informational ONLY... where no user interaction or response is expected.)

This feature will needs to have the following requirements:
1. Ability to pass in an attribute that controls the display of the 'X' icon. (default is on/visible)
2. Ability to pass in an attribute that controls the ability to close the modal window by clicking outside of it. (default is off/disabled)

Cc
@kpmurphh @stolve

**Comment by grahamhency** [comment]
The only concern I have with this request is around this:

> Ability to pass in an attribute that controls the ability to close the modal window by clicking outside of it. (default is off/disabled)

This the default functionality for all the modals on the Mobile side of things.. (we just treat it as a cancel for forms). Setting this to not be the default behavior would be a UX change for us.

The other thing I could see being an issue is that if this is set as the default, and there is an instance where we hide the close icon, then there would be no way to close the modal... which maybe is intended, but that (to me) sounds like more of an edge case than the latter.

Any thoughts on this @mobi/tangoe-ux-ui??

**Comment by cosmicdust73** [comment]
In regards to your second point, yes that is the intent. Some modals require that there be no way for a user to cancel out of them. They need to make a yes or no decision, and allowing them to cancel would just cause confusion during the flow... especially if triggered by the 'X' or by clicking outside, as opposed to an actual 'Cancel' button.

For the first point, yes in this case there is going to be a UX change in Modal... but I am not at all concerned about it, as we already provide TWO ways in Tangoe DS for a user to cancel out of a modal. (i.e. the 'X' as well as the 'Cancel' button) Having a 3rd way, which in some cases could be triggered accidentally by a user who accidentally clicks the background, is far more concerning to me... especially if it results in the loss of data that was possibly entered into the form. Happy to discuss further to hear other viewpoints.

**Comment by cosmicdust73** [comment]
@grahamhency We just received further confirmation from our Product and user stakeholder team on Ordering that the above changes to goponent modal windows need to be contributed, if not by the Ordering DEV team, then by someone else managing Goponent updates. 

At least one stakeholder user has recently raised concerns about the current behavior, where their mouse accidentally clicked outside of the window, resulting in the window closing and them losing their form data entry.  The default behavior should NOT allow users to close the window by clicking outside... but we can add that as an option in the rare cases where the modal window only contains Help-like, informational read-only data.

While this is a UX change to current Mobile behavior, I think the change is for the better. I just ran into this same issue myself using some other website the other day. Even though I was not 'clicking' on the outside of the window... what happened was that the onmouseup event from my mouse click on the content area of the modal would trigger if my cursor drifted outside the modal.  This caused the window to keep closing and was VERY annoying. :)
Cc @stolve @kpmurphh @patrick-lewandowski

**Comment by grahamhency** [comment]
> At least one stakeholder user has recently raised concerns about the current behavior, where their mouse accidentally clicked outside of the window, resulting in the window closing and them losing their form data entry. 

Sounds like someone got trigger happy.

If this is the behavior we wish to have then that's fine, I just wanted to do my due diligence and confirm that we're accepting the behavior change for Mobile.

This issue is up for grabs for anyone that can pick it up.
