### ISSUE TITLE
[BUG] GoTable doesnt display 'false' values for a boolean type column.

### ISSUE THREAD

**Issue by Ashygoyal** [mobi/goponents#681]
**Describe the bug**
Lets say there is a column in the go-table, which is of type boolean i.e. that particular field in the API is boolean, the go-table shows only the values that are `true`. It displays an empty string if the value is `false`. 

As a workaround, if you include an ng-template for that column, the `false` values start to show up.
But if in case you want to show `false` as `False` or `FALSE` (basically you want to pipe it), the table logic by-passes that expression/ logic.

**To Reproduce**
1. In your implementation of the go-table, include a column that displays boolean values.
2. Feed data into it with a mix of true and false values. Check the UI. You'll notice that only truthy (`true`) values are visible.

**Expected behavior**
The go-column should display `false` values.
Suggestion, we can replace `true/ false` with `Yes/No` to avoid any reserved keyword clashes, in case it makes things easier.

**Comment by grahamhency** [comment]
@Ashygoyal, were you still planning on working this?

**Comment by Ashygoyal** [comment]
> @Ashygoyal, were you still planning on working this?

@grahamhency , apologies, i wont be working on this at the moment, I'll unassign it from my name so that its free for anyone else to pick this up.
