### ISSUE TITLE
[Feature] Add maxlength & minlength binding options for go-input

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#691]
### What is the feature that you would like to propose?
I am requesting that we expose the `maxlength` and `minlength` attributes for `input`s

### Describe the solution you'd like
On a `go-input`, be able to pass a value for both `maxlength` and `minlength` and have it apply to the `input` element inside the `go-input`.

**Comment by Ashygoyal** [comment]
@grahamhency - One query:
In case, the user wants to set both the `minlength `and `maxlength `property at the same time and suppose he sets `minlength `more than the `maxlength`,
shall we default the `minlegth `to **zero**
or
shall we default the `minlegth `as **equal to** `maxlength`?

**Comment by Ashygoyal** [comment]
Also @grahamhency , should we put in a go-hint or something from the goponents side, if the user is exceeding the maxlength property?
He would keep on pressing keys, but it wont put any character in the input field, can cause a bit of confusion.
Or is it upto the developer to handle this their way?

**Comment by grahamhency** [comment]
> Also @grahamhency , should we put in a go-hint or something from the goponents side, if the user is exceeding the maxlength property?
> He would keep on pressing keys, but it wont put any character in the input field, can cause a bit of confusion.
> Or is it upto the developer to handle this their way?

I think this will be up to implementation to handle because the reason for the limitations are unknown to us.

> default values of both the properties, would be
> minlength = 0
> maxlength = 524288

I think these should be the defaults. If the implementor wishes to use the Angular validators, then they would just not set these bindings on the component and let Angular handle the validations.
