### ISSUE TITLE
[Feature] WYSIWYG Editor Component

### ISSUE THREAD

**Issue by cosmicdust73** [mobi/goponents#727]
### Feature
Product/UX has a need for a WYSIWYG editor component.

### Purpose
This feature will be used within the Telecom Ordering application for the purposes of editing the email template/preview email that is sent out to order contacts.

### Describe the solution you'd like
Ideally, the editor would be something similar to [tinyMCE](https://www.tiny.cloud/) supporting similar features. 

_**Example:**_
> This feature will needs to have the following requirements:
> 1. Editing of text
> 2. Inserting of tables should be possible with n # of row(s) and col(s)
> 3. Default content must reflect content as defined in the respective Telecom Ordering email template.
> 3. Basic text formatting would be **nice to have**.
> 4. Would also **be nice to have** some areas of the email to be locked down (uneditable), while other areas can be updated by the user.

Please tag anyone else who should be aware of this feature. This may also be needed in the Mobile End User Portal Dashboard functionality... Phase 2 or beyond, to support announcement editing.
@stolve @grahamhency @StevenUlmer

**Comment by grahamhency** [comment]
@cosmicdust73, seems like maybe we can just use TinyMCE for this? We use it in Mobile now. Not sure what we might need to add to it that would make it necessary to have it as a Goponent. This would be similar to how we implement virtual scroll by using the Material CDK.

**Comment by cosmicdust73** [comment]
@grahamhency makes sense to me. Just going through the normal request process. If the team feels that TinyMCE can be used directly (i.e. not turned into a Goponent), I can inform the Ordering Dev team on that decision.

**Comment by grahamhency** [comment]
@mobi/tangoe-ux-ui I am going to put up a PR to document that we're just going to use TinyMCE for this (similar to what we're doing for the [virtual scroll](https://tangoe.design/ui-kit/virtual-scroll)). This way we will at least have it documented to use TinyMCE and if we need to do something else in the future we've got a spot for it.
