### ISSUE TITLE
[BUG] go-select border issue for dark theme

### ISSUE THREAD

**Issue by amitpatra91** [mobi/goponents#755]
**Describe the bug**
In dark theme white border color is not showing while option will display at bottom

**Expected behavior**
Border color should display for both top and bottom. 

**Screenshots**
<img width="284" alt="ng-select-bottom" src="https://user-images.githubusercontent.com/33975358/108217286-6bd3c200-7159-11eb-8d20-f0b3800641df.PNG">

**Comment by grahamhency** [comment]
Tagging @mobi/tangoe-ux-ui for visibility here.

**Comment by grahamhency** [comment]
@amitpatra91, @mobi/tangoe-ux-ui this is _temporarily_ address in #758 until we figure out a better solution for these type of dark-themed dropdowns/pop-ups. The changes in #758 look like this:

![Screen Shot 2021-02-17 at 4 23 27 PM](https://user-images.githubusercontent.com/11966331/108273975-4e472e00-7142-11eb-8423-986e5c677701.png)

I am not going to close this issue as we will need to polish this, but just posting for reference.

**Comment by grahamhency** [comment]
Closing this issue. We can address a more thought out dark theme in a new issue.
