### ISSUE TITLE
[Chore] Form Control Input Font Color Changes

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#757]
### What general chore or task would you like to see performed?
The following form control font colors need to be changed to #313536:

- Basic input active color - currently #000
- Timepicker and datepicker active color - currently #000
- Textarea active color - currently #000
- Select active color - currently #333 
- Select dropdown menu items color - currently #333 

By active I mean when the form control has something in it.

**Comment by grahamhency** [comment]
Say whaaaat.
