### ISSUE TITLE
[Feature] Add Background Color to Go-Card Headers

### ISSUE THREAD

**Issue by deotte** [mobi/goponents#772]
### What is the feature that you would like to propose?
Currently, the `go-card-header` inside of `go-cards` does not support having a background color set or passed in. It would be awesome to be able to pass in, or have a default background color set.

_**Example:**_
> The groups/show interface in the mobile application has long vertical panels inside of each accordion. It would be great to mimic that.

<img width="1532" alt="Screen Shot 2021-03-09 at 11 41 58 AM" src="https://user-images.githubusercontent.com/31936704/110518151-c49fd600-80d9-11eb-9fde-28fc19b2db9b.png">

### Describe the solution you'd like
Add ability to pass in a background color.

**Comment by grahamhency** [comment]
@mobi/tangoe-ux-ui this is something we have in quite a few places in our app. I'm open to various different options, but figured we could discuss it here. 

One idea is just to implement this with our current card design and call it good, we could look at adding a header background, or maybe we look at how this data is displayed and organized so we can get away from this stacked card design?

Thoughts?

**Comment by grahamhency** [comment]
@deotte we've decided against going this route with the cards. In our case, please just use the `go-card` header as it is.
