### ISSUE TITLE
[Chore] Add external links to subnav

### ISSUE THREAD

**Issue by stolve** [mobi/goponents#783]
### What general chore or task would you like to see performed?
I want the  ability to add external links to the sublevel navigation. This should also include the external link icon (launch) where the drop down icon is.

This is in reference to a Telecom Ordering issue on jira ticket PROV-4410

**Comment by grahamhency** [comment]
![Screen Shot 2021-05-03 at 11 12 06 AM](https://user-images.githubusercontent.com/11966331/116894744-676b6100-ac00-11eb-8d94-367c36a528e0.png)

Technically this already exists.. but it does look like we might need to adjust spacing.

**Comment by stolve** [comment]
There is a little more involved to this issue that we can discuss on the call tomorrow.

**Comment by stolve** [comment]
@grahamhency I am going to share this issue with Sudheep from the fixed ordering dev team so that he can provide further context to the problem they are having.

**Comment by grahamhency** [comment]
Closing this because Sudheep opened this duplicate issue: #792
