### ISSUE TITLE
[Chore] Space between cards inside of large offcanvas

### ISSUE THREAD

**Issue by stolve** [mobi/goponents#788]
### What general chore or task would you like to see performed?
Currently the spacing between multiple cards in a large overlay is 2rem, with the exception of the top card which sit 16px below the header bar. When inside a large overlay the cards should have 1rem between them.

**Comment by grahamhency** [comment]
@stolve I believe this can be achieved using the `go-container--form` class yes? It's the same spacing as form elements.

**Comment by grahamhency** [comment]
Very basic example of usage:

```html
<div class="go-container go-container--form">
  <go-card class="go-column go-column--100"><go-card>
</div>

**Comment by grahamhency** [comment]
I think the css above solves this issue, closing.
