### ISSUE TITLE
GoSideNav external link menu item to be capable of opening a new window and return a reference to it. 

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#791]
If external link menu item returns a reference to the newly opened window, it will help us to manage the new window as per required.

**Comment by grahamhency** [comment]
Hey @sudheepdivakargithub in the future, please use the template provided in the issue template when creating issues.

In regards to your request, his is possible today.

https://tangoe.design/ui-kit/layout/side-nav/#usage

If you look at the documentation for a `NavItem` you can see there is a property for `externalLinkTarget`. If you pass a custom name for the tab into that property the link in the side nav will open it in a new tab and if the user tries to open the tab again it will open the already existing tab.
