### ISSUE TITLE
[BUG] Side navigation active indicator not appearing for dropdown navigation items

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#812]
**Describe the bug**
The brand color side navigation active indicator does not appear for navigation items with sub-navigation items, according to tangoe.design.

**To Reproduce**
1. Upon visiting tangoe.design, the active indicator can be seen next to "Getting Started"
2. If you leave this page by selecting "Standards" or any other dropdown navigation item and then select a sub-navigation item, the active indicator disappears. 

**Expected behavior**
The active indicator should appear next to the navigation item the user is currently visiting regardless of if they're visiting the primary page of that item or a sub-navigation page.

**Screenshots**
<img width="258" alt="Screen Shot 2021-06-22 at 10 41 58 AM" src="https://user-images.githubusercontent.com/9440696/122945432-9374aa00-d346-11eb-8682-b02fd6645b0c.png">
<img width="257" alt="Screen Shot 2021-06-22 at 10 42 30 AM" src="https://user-images.githubusercontent.com/9440696/122945396-8c4d9c00-d346-11eb-849b-7eec94cbe190.png">

**Comment by grahamhency** [comment]
Thanks for the thorough issue.. no idea when this broke lol.

**Comment by grahamhency** [comment]
To verify, you're requesting this indicator to appear on child menu options and not the root base ones right?

<img width="258" alt="Screen Shot 2021-08-12 at 5 08 39 PM" src="https://user-images.githubusercontent.com/11966331/129270176-28c7a0f1-8de7-41fc-bd3f-500e6a493c12.png">

**Comment by cosmicdust73** [comment]
> To verify, you're requesting this indicator to appear on child menu options and not the root base ones right?
> 
> <img alt="Screen Shot 2021-08-12 at 5 08 39 PM" width="258" src="https://user-images.githubusercontent.com/11966331/129270176-28c7a0f1-8de7-41fc-bd3f-500e6a493c12.png">

@grahamhency no this request is only to ensure that the base/root element gets the highlight indicator when one of its children is the active page. That functionality has been broken for quite some time now. (it was working at one point)
