### ISSUE TITLE
Bug: Go Loader does not work properly in Safari

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#82]
## Problem
In Safari, the `go-loader` component renders solid black.

<img width="422" alt="Screen Shot 2019-07-23 at 4 19 48 PM" src="https://user-images.githubusercontent.com/11966331/61744640-ccc0cb80-ad65-11e9-9b10-d2c0141545cf.png">

**Comment by AlexOverbeck** [comment]
I can take a look at this one today.
