### ISSUE TITLE
[Feature] Ability to have Loading State in Action Sheet Dropdown

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#836]
### What is the feature that you would like to propose?
We are looking to be able to have a loader inside of an action sheet dropdown, specifically for the use case where the 'actions' will be fetched from an API to a 3rd party application, such as Flowable.

_**Example:**_
<img width="225" alt="Screen Shot 2021-09-03 at 1 46 43 PM" src="https://user-images.githubusercontent.com/9440696/132046727-eb5990c7-3216-4940-aa0d-7b6df33c5bef.png">

**Comment by grahamhency** [comment]
This is already possible. You can conditionally render a `go-loader` inside of the `go-accordion-panel` until the content is loaded. See [this example](https://tangoe.design/ui-kit/accordion/panel/#delayed-loading) in the docs, specifically using `<ng-template #panelContent></template` inside of the panel.
