### ISSUE TITLE
Splitbutton - Options label for alternative actions wraps when its longer than the main action label. 

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#848]
Options label for alternative actions wraps when its longer than the main action label. 

**To Reproduce**
1. Setup Split Button component. Provide splitButtonOptions with options label longer than the main action label.
2. Click on the dropdown to open the alternate options. 
3. Notice that the option label wraps. 
4.

**Expected behavior**
Options label should be in a single line. 

**Screenshots**
![Splitbutton](https://user-images.githubusercontent.com/4224079/142566029-9287bae1-cce5-40de-b178-9ffcbc74c6e3.PNG)

**Comment by sudheepdivakargithub** [comment]
@stolve  @grahamhency . 
Hey let me know if this is okay. 
![image](https://user-images.githubusercontent.com/4224079/148064285-7a3789f8-ad6b-4902-b6b5-a43d403acf52.png)

Took of max-width from __menu-option and set white-space: nowrap on __menu class.

**Comment by grahamhency** [comment]
@sudheepdivakargithub, please put up a pull request with the proposed changes. This comment is not sufficient.

**Comment by sudheepdivakargithub** [comment]
I know. That is to be done. Prior to that I thought of getting the feedback on the result and check if this is line with UI/UX expectation.
