### ISSUE TITLE
[Chore] Accordion Styling (Normal & Dark theme)

### ISSUE THREAD

**Issue by stolve** [mobi/goponents#884]
The accordion component in Goponents does not have the approved UX styling. Please see the list below for updates:

**Default Accordion**

- Header should be equivalent to an H4 (18px - 1.125rem). Currently it is using 1.2rem (19.2px).
- The body contains unexpected padding around the content (1.5rem top/bottom) where UX outlined  in as 1rem all around.
- The body text should always be 14px (0.875rem) default.

**Slim Accordion**

- Header should be equivalent to an H5 (14px - 0.875rem). Currently it is using 1rem (16px).
- Header section padding should be 10px (0.625rem) top and bottom and 16px(1rem) left and right
- The body text should always be 14px (0.875rem) default.
- The padding around the body should be 16px (1rem) all around.

**Dark Theme**

- Follows the above rules with the following additions
- Header background color when collapsed is #313536
- Header background color hovered when collapsed is #313536 3.5% darkened (HEX equivalent #292C2D)
- Header background color when expanded is #181C1C.
- Header background color hovered when expanded is #181C1C 3.5% darkened (HEX equivalent #101212)
- border-radius needs to be 0px when the accordion reached the full width of the off-canvas container.

**Comment by stolve** [comment]
UX has made edits to the header background color when expanded and wen expanded and hovered in the Dark Theme.

**Comment by Pooja-kj** [comment]
i will check on that
