### ISSUE TITLE
[Chore] Read-only state for form fields

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#900]
### What general chore or task would you like to see performed?
**Describe the bug**
A read-only state is needed for form fields - text fields, selects, typeaheads, textareas, multiselect, etc. (Excludes selection controls)

The read only state styling is as follows:
- The text color is #313536 
- The background and border color of the input area are the same as the disabled state.

**Comment by stolve** [comment]
This ticket is not longer needed. Changes to align with the mobile store BS5 deign system have been placed in individual tickets per component. This ticket can be closed.
