### ISSUE TITLE
[BUG] Background color of a disabled select field to be #F0F0F0

### ISSUE THREAD

**Issue by amit-patra** [mobi/goponents#924]
**Describe the bug**
The background color of a disabled select field to be #F0F0F0 instead of #F9F9F9

**To Reproduce**
1. Go to 'https://tangoe.design/ui-kit/forms/select'
2. Scroll down to 'Disable Component'
4. See the background color css

**Expected behavior**
The background color CSS should be **#F0F0F0**

**Screenshots**
![image](https://github.com/mobi/goponents/assets/35175564/35b64f2f-3733-487b-8000-0450578ba29b)

![image](https://github.com/mobi/goponents/assets/35175564/42016b7b-e72d-492e-b4bf-3cd7011a9b5a)

**Comment by RonMichaud** [comment]
@amit-patra please make this change and open a pull
